"""English/Vietnamese pairs for activity-log and background status text."""

UI_LOG_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    ("[UI] event loop stall {} ms (processing={}, archive_active={})", "[UI] vòng lặp giao diện bị khựng {} ms (đang_xử_lý={}, lưu_trữ_đang_chạy={})"),
    ("Removed intermediate OCR artifact: {}", "Đã xóa tệp OCR trung gian: {}"),
    ("Could not remove intermediate OCR artifact: {}", "Không thể xóa tệp OCR trung gian: {}"),
    ("OCR pool init failed (will retry on first OCR): {}", "Khởi tạo nhóm OCR thất bại (sẽ thử lại ở lần OCR đầu): {}"),
    ("OCR pool shutdown error: {}", "Lỗi khi đóng nhóm OCR: {}"),
    ("Correction init error: {}", "Lỗi khởi tạo sửa văn bản: {}"),
    ("correction_engine import failed: {}", "Nhập correction_engine thất bại: {}"),
    ("table_anchored_merger import failed: {}", "Nhập table_anchored_merger thất bại: {}"),
    ("Export pool shutdown error: {}", "Lỗi khi đóng nhóm xuất: {}"),
    ("[ModelManager] No loader registered for '{}'", "[Quản lý mô hình] Chưa đăng ký bộ tải cho '{}'"),
    ("[ModelManager] Load '{}' failed: {}", "[Quản lý mô hình] Tải '{}' thất bại: {}"),
    ("[ModelManager] Release '{}' failed: {}", "[Quản lý mô hình] Giải phóng '{}' thất bại: {}"),
    ("Parallel OCR: {} page workers for {} pages", "OCR song song: {} worker cho {} trang"),
    ("OCR {} pages...", "OCR {} trang..."),
    ("OCR {}/{} pages (scan/mixed) @ {} DPI via {}-worker pool...", "OCR {}/{} trang (scan/mixed) @ {} DPI qua pool {} worker..."),
    ("OCR {} pages (scan/mixed) @ {} DPI with one worker...", "OCR {} trang (scan/mixed) @ {} DPI single-worker..."),
    ("Queueing Export: {}", "Đang đưa vào hàng đợi xuất: {}"),
    ("Archive: workflow reset (temp wiped)", "Lưu trữ: đã đặt lại quy trình (đã xóa dữ liệu tạm)"),
    ("Archive: Found {} PDF file(s) recursively in {}", "Lưu trữ: tìm thấy {} file PDF trong {} và các thư mục con"),
    ("Archive: pipeline started on {} files (KIE={})", "Lưu trữ: đã chạy quy trình cho {} file (KIE={})"),
    ("Archive: ZIP fast-path started on {} file(s) (KIE-only, KIE={})", "Lưu trữ: đã chạy luồng nhanh ZIP cho {} file (chỉ KIE, KIE={})"),
    ("Archive: Step 1→2 pipeline started on {} segments (KIE={})", "Lưu trữ: đã chạy quy trình Bước 1→2 cho {} đoạn (KIE={})"),
    ("Archive: ZIP reopened — {} doc(s) from {} (input: {})", "Lưu trữ: đã mở lại ZIP — {} văn bản từ {} (đầu vào: {})"),
    ("Archive: ZIP→Repository import started — {} doc(s)", "Lưu trữ: bắt đầu nhập ZIP→Kho — {} văn bản"),
    ("Starting Pipeline (Parallel OCR files: {}, ~{} OCR workers)...", "Đang chạy quy trình (file OCR song song: {}, ~{} OCR worker)..."),
    ("Re-running {}...", "Đang xử lý lại {}..."),
    ("Pipeline: streaming {} file(s), {} parallel OCR", "Quy trình: đang xử lý luồng {} file, {} OCR song song"),
    ("All files finished.", "Đã xử lý xong tất cả file."),
    ("Unknown screen: {}", "Màn hình không xác định: {}"),
    ("LightGBM: loading", "LightGBM: đang tải"),
    ("LayoutLMv3: loading in background", "LayoutLMv3: đang tải nền"),
    ("Saving corrected PDF: {}", "Đang lưu PDF đã sửa: {}"),
    ("Archive: folder pick cancelled (no identity)", "Lưu trữ: đã hủy chọn thư mục (chưa có mã định danh)"),
    ("Archive: ZIP fast-path has no document list", "Lưu trữ: luồng nhanh ZIP không có danh sách văn bản"),
    ("Archive: import to Repository failed: {}", "Lưu trữ: nhập vào Kho thất bại: {}"),
    ("Archive: ZIP→Repository import — {} doc(s) skipped without .json.zst companion", "Lưu trữ: nhập ZIP→Kho — bỏ qua {} văn bản không có file .json.zst đi kèm"),
    ("Stopping requested... waiting for current processes to finish.", "Đã yêu cầu dừng... đang chờ các tiến trình hiện tại kết thúc."),
    ("  > Output exists ({}). Skipping OCR.", "  > Đầu ra đã tồn tại ({}). Bỏ qua OCR."),
    ("  > OCR Failed: {}", "  > OCR thất bại: {}"),
    ("Initializing OCR file pool ({} parallel files, ~{} OCR workers)", "Đang khởi tạo nhóm OCR ({} file song song, ~{} OCR worker)"),
    ("Output exists {}. Skipping OCR.", "Đầu ra {} đã tồn tại. Bỏ qua OCR."),
    ("OCR Success: {} ({}s)", "OCR thành công: {} ({} giây)"),
    ("Correction Success: {} ({}s)", "Sửa lỗi thành công: {} ({} giây)"),
    ("Could not persist translate toggle: {}", "Không lưu được tùy chọn dịch: {}"),
    ("[digitization-warmup] LightGBM splitter ready in {}s", "[khởi động-số-hóa] bộ tách LightGBM sẵn sàng sau {} giây"),
    ("Correction: loading", "Sửa lỗi: đang tải"),
    ("LightGBM: ready", "LightGBM: sẵn sàng"),
    ("LayoutLMv3: ready", "LayoutLMv3: sẵn sàng"),
    ("Failed to save settings: {}", "Không lưu được cài đặt: {}"),
    ("Archive: All {} files processed", "Lưu trữ: đã xử lý toàn bộ {} file"),
    ("Corrected PDF saved: {}", "Đã lưu PDF đã sửa: {}"),
    ("Failed to save: {}", "Lưu thất bại: {}"),
    ("Error saving PDF: {}", "Lỗi khi lưu PDF: {}"),
    ("Archive: reset failed: {}", "Lưu trữ: đặt lại thất bại: {}"),
    ("Warming KIE ({}) for ZIP fast-path...", "Đang khởi động KIE ({}) cho luồng nhanh ZIP..."),
    ("Archive: Export failed: {}", "Lưu trữ: xuất thất bại: {}"),
    ("Archive: could not release Repository index: {}", "Lưu trữ: không thể giải phóng chỉ mục Kho: {}"),
    ("Archive: ZIP load rejected — {}", "Lưu trữ: từ chối nạp ZIP — {}"),
    ("Archive: ZIP load failed — {}", "Lưu trữ: nạp ZIP thất bại — {}"),
    ("  > OCR completed in {}s", "  > OCR hoàn tất sau {} giây"),
    ("  > Correction completed in {}s", "  > Sửa lỗi hoàn tất sau {} giây"),
    ("Skip correction: digital PDF ({})", "Bỏ qua sửa lỗi: PDF số ({})"),
    ("Correction Error: {}", "Lỗi sửa văn bản: {}"),
    ("Metadata extraction error: {}", "Lỗi bóc tách metadata: {}"),
    ("Export Success: {} ({}s)", "Xuất thành công: {} ({} giây)"),
    ("Export Failed: {}", "Xuất thất bại: {}"),
    ("Export Exception: {}", "Ngoại lệ khi xuất: {}"),
    ("Translation Success: {} ({}s, {})", "Dịch thành công: {} ({} giây, {})"),
    ("Translation Exception: {}", "Ngoại lệ khi dịch: {}"),
    ("Repository refresh failed: {}", "Làm mới Kho thất bại: {}"),
    ("[digitization-warmup] LightGBM splitter warmup failed: {}", "[khởi động-số-hóa] khởi động bộ tách LightGBM thất bại: {}"),
    ("Correction: ready", "Sửa lỗi: sẵn sàng"),
    ("LightGBM: failed", "LightGBM: thất bại"),
    ("LayoutLMv3: failed", "LayoutLMv3: thất bại"),
    ("Archive leave guard failed: {}", "Kiểm tra trước khi rời màn hình lưu trữ thất bại: {}"),
    ("Failed to load settings: {}", "Không tải được cài đặt: {}"),
    ("ZIP fast-path aborted: {}", "Đã hủy luồng nhanh ZIP: {}"),
    ("Archive: could not reopen Repository index: {}", "Lưu trữ: không thể mở lại chỉ mục Kho: {}"),
    ("Archive: reset before ZIP load failed: {}", "Lưu trữ: đặt lại trước khi nạp ZIP thất bại: {}"),
    ("  > Skip correction: digital PDF (text native)", "  > Bỏ qua sửa lỗi: PDF số (text gốc)"),
    ("  > Correction failed: {}", "  > Sửa lỗi thất bại: {}"),
    ("OCR Fail: {}", "OCR thất bại: {}"),
    ("OCR post-processing error: {}", "Lỗi hậu xử lý OCR: {}"),
    ("Translation Failed: {}", "Dịch thất bại: {}"),
    ("Correction: failed", "Sửa lỗi: thất bại"),
    ("[{}] Extracting text layer (no re-OCR, signature preserved)...", "[{}] Đang trích xuất lớp chữ (không OCR lại, giữ nguyên chữ ký)..."),
    ("[{}] KIE done ({} fields)", "[{}] KIE hoàn tất ({} trường)"),
    ("  > Export completed: {}", "  > Xuất hoàn tất: {}"),
    ("  > Export Failed: {}", "  > Xuất thất bại: {}"),
    ("  [Exp] {}", "  [Xuất] {}"),
    ("[{}] No text layer found — skipping KIE (signature would be lost by re-OCR). Metadata kept from ZIP.", "[{}] Không tìm thấy lớp chữ — bỏ qua KIE (OCR lại sẽ làm mất chữ ký). Giữ metadata từ ZIP."),
    ("[{}] ZIP fast-path failed: {}", "[{}] Luồng nhanh ZIP thất bại: {}"),
    ("Archive: cleanup after Repository import failed: {}", "Lưu trữ: dọn dẹp sau khi nhập Kho thất bại: {}"),
    ("[{}] signer-page selector failed: {}", "[{}] Bộ chọn trang ký thất bại: {}"),
    ("Archive: unsaved-change check failed: {}", "Lưu trữ: kiểm tra thay đổi chưa lưu thất bại: {}"),
    ("Archive: unsaved-change prompt failed: {}", "Lưu trữ: hộp thoại thay đổi chưa lưu thất bại: {}"),
    ("[STEP2-SELECT] {}", "[BƯỚC2-CHỌN] {}"),
    ("Archive Step 3: signed {}/{} PDF files", "Lưu trữ Bước 3: đã ký {}/{} file PDF"),
    ("Archive Step 3: signing with TSA {}", "Lưu trữ Bước 3: đang ký với TSA {}"),
    ("Archive Step 3: batch time source fixed to local computer time after TSA connection failure", "Lưu trữ Bước 3: đã chuyển nguồn thời gian của lô sang giờ máy tính sau khi kết nối TSA thất bại"),
    ("Archive Step 3: signing without TSA; using local computer time", "Lưu trữ Bước 3: ký không dùng TSA; sử dụng giờ máy tính"),
    ("[step1-ui] applied {} split suggestion(s) in {}s", "[bước1-ui] đã áp dụng {} gợi ý tách sau {} giây"),
    ("[step1-ui] kept source PDF viewer; skipped full OCR PDF re-render", "[bước1-ui] giữ trình xem PDF nguồn; bỏ qua dựng lại toàn bộ PDF OCR"),
    ("[step1] OCR cancelled.", "[bước1] Đã hủy OCR."),
    ("[step1-ui] source viewer missing; loading OCR PDF for review", "[bước1-ui] thiếu trình xem nguồn; đang tải PDF OCR để kiểm tra"),
    ("[step1-ocr] bounded queue: max {} page(s) in flight", "[bước1-ocr] hàng đợi giới hạn: tối đa {} trang đang xử lý"),
    ("[step1] assembled cached OCR PDF/JSON in {}s", "[bước1] đã ghép PDF/JSON OCR từ cache sau {} giây"),
    ("[step1-splitter] doc_start predicted {} start(s) on {} page(s) in {}s", "[bước1-bộ-tách] dự đoán {} điểm bắt đầu trên {} trang sau {} giây"),
    ("[step1-ocr] crashed: {}\n{}", "[bước1-ocr] bị lỗi: {}\n{}"),
    ("[step1-splitter] warmed LightGBM models in {}s", "[bước1-bộ-tách] đã khởi động mô hình LightGBM sau {} giây"),
    ("[step1-splitter] waiting for LightGBM warmup...", "[bước1-bộ-tách] đang chờ khởi động LightGBM..."),
    ("[step1-splitter] failed: {}", "[bước1-bộ-tách] thất bại: {}"),
    ("[step1-splitter] warmup failed: {}", "[bước1-bộ-tách] khởi động thất bại: {}"),
    ("[step1-ocr] page {}: {}", "[bước1-ocr] trang {}: {}"),
    ("[step1-ocr] submit failed: {}", "[bước1-ocr] gửi tác vụ thất bại: {}"),
    ("ERRORS:", "LỖI:"),
    ("WARNINGS:", "CẢNH BÁO:"),
    ("{} pages", "{} trang"),
    ("{} documents", "{} tài liệu"),
    ("Stored: {}", "Lưu kho: {}"),
    ("{} dossiers · {} documents · {} pages · {} passages", "{} hồ sơ · {} tài liệu · {} trang · {} đoạn"),
    ("Accuracy: {}", "Độ chính xác: {}"),
    ("Bulk signing: loaded {} PDF(s) from {}", "Ký hàng loạt: đã tải {} file PDF từ {}"),
    ("Bulk signing: starting {} file(s) → {} (with auto-OCR)", "Ký hàng loạt: bắt đầu {} file → {} (có OCR tự động)"),
    ("Bulk signing: starting {} file(s) → {} (no OCR)", "Ký hàng loạt: bắt đầu {} file → {} (không OCR)"),
    ("Bulk signing: signed {}/{} PDF file(s)", "Ký hàng loạt: đã ký {}/{} file PDF"),
    ("Bulk signing: signed {}/{} PDF file(s); OCR applied to {} file(s)", "Ký hàng loạt: đã ký {}/{} file PDF; đã OCR {} file"),
    ("Archive Step 3: dossier information updated", "Lưu trữ Bước 3: đã cập nhật thông tin hồ sơ"),
    ("Archive Step 3: dossier information updated; renamed {} signed PDF file(s)", "Lưu trữ Bước 3: đã cập nhật thông tin hồ sơ; đổi tên {} file PDF đã ký"),
    ("Bulk signing: cannot load settings: {}", "Ký hàng loạt: không tải được cài đặt: {}"),
    ("Bulk signing: cannot save settings: {}", "Ký hàng loạt: không lưu được cài đặt: {}"),
    ("Signing: cannot load signature settings: {}", "Ký số: không tải được cài đặt chữ ký: {}"),
    ("Signing: cannot reload config: {}", "Ký số: không thể tải lại cấu hình: {}"),
    ("Signing: TSA unavailable; user confirmed signing with local computer time", "Ký số: TSA không khả dụng; người dùng đã xác nhận ký bằng giờ máy tính"),
    ("Signing: cannot load signature templates: {}", "Ký số: không tải được mẫu chữ ký: {}"),
    ("Repository: ZIP import failed — {}", "Kho: nhập ZIP thất bại — {}"),
    ("Archive: imported into Repository — {}/{}", "Lưu trữ: đã nhập vào Kho — {}/{}"),
    ("Archive: ZIP exported — {} PDF + Excel", "Lưu trữ: đã xuất ZIP — {} PDF + Excel"),
    ("({} skipped without source)", "({} bị bỏ qua do thiếu file nguồn)"),
    (", {} duplicates", ", {} trùng"),
    ("Repository: ZIP imported — {}/{} from {} dossier ZIPs", "Kho: đã nhập ZIP — {}/{} từ {} hồ sơ ZIP"),
    ("Repository: chunker import failed: {}", "Kho: nhập bộ chia đoạn thất bại: {}"),
    ("Repository: extract blocks failed: {}", "Kho: trích xuất khối thất bại: {}"),
    ("Repository: release index failed: {}", "Kho: giải phóng chỉ mục thất bại: {}"),
    ("Repository: reopen index failed: {}", "Kho: mở lại chỉ mục thất bại: {}"),
    ("DB migration skipped (non-fatal): {}", "Đã bỏ qua migration CSDL (không nghiêm trọng): {}"),
    ("Repository: could not reopen index: {}", "Kho: không thể mở lại chỉ mục: {}"),
    ("Repository: reload index failed: {}", "Kho: tải lại chỉ mục thất bại: {}"),
)


# Messages emitted by processing backends and surfaced in the activity log.
UI_BACKEND_LOG_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    # Metadata and archival digitization
    ("Metadata: Detected doc type = {}", "Metadata: đã nhận diện loại văn bản = {}"),
    ("Metadata: {}", "Metadata: {}"),
    ("Metadata: JSON not found: {}", "Metadata: không tìm thấy JSON: {}"),
    ("Metadata: No pages in JSON", "Metadata: JSON không có trang"),
    ("Metadata: No lines on page 1", "Metadata: trang 1 không có dòng chữ"),
    ("Metadata: No lines on header pages", "Metadata: các trang đầu không có dòng chữ"),
    ("Metadata: Failed to load JSON: {}", "Metadata: không tải được JSON: {}"),
    ("Found {} PDF file(s)", "Tìm thấy {} file PDF"),
    ("Warming KIE ({})...", "Đang khởi động KIE ({})..."),
    (">>> Pipeline START <<<", ">>> BẮT ĐẦU QUY TRÌNH <<<"),
    ("=== Archive complete in {}s ({} files) ===", "=== Hoàn tất lưu trữ sau {} giây ({} file) ==="),
    ("[{}] KIE clean signer page only: OCR page {} with annots=False; full-document OCR is reused", "[{}] KIE chỉ làm sạch trang ký: OCR trang {} với annots=False; tái sử dụng OCR toàn văn bản"),
    ("[{}] KIE clean signer page ready: page={}, lines={}, words={}", "[{}] Trang ký sạch cho KIE đã sẵn sàng: trang={}, dòng={}, từ={}"),
    ("No input files", "Không có file đầu vào"),
    ("Warming OCR pool...", "Đang khởi động nhóm OCR..."),
    ("Using Step 1 OCR cache — OCR pool startup skipped", "Dùng OCR cache từ Bước 1 — không khởi động OCR lại"),
    ("Correction: OFF (configuration) — warmup skipped", "Sửa chính tả: TẮT (theo cấu hình) — bỏ qua warmup correction"),
    ("[{}] KIE selected_pages={} (signer_page={}, score={})", "[{}] KIE selected_pages={} (trang_ký={}, điểm={})"),
    ("[{}] KIE clean signer page skipped: page={} outside page_count={}", "[{}] Bỏ qua làm sạch trang ký cho KIE: trang={} nằm ngoài page_count={}"),
    ("[{}] KIE clean signer page skipped: using Step 1 OCR cache", "[{}] Bỏ qua làm sạch trang ký cho KIE: đang dùng OCR cache từ Bước 1"),
    ("[{}] KIE clean signer page skipped: page {} has no PDF annotations/widgets", "[{}] Bỏ qua làm sạch trang ký cho KIE: trang {} không có chú thích/widget PDF"),
    ("[{}] assemble payload serialized in {}s", "[{}] Đã tuần tự hóa dữ liệu ghép sau {} giây"),
    ("Assembled (cached OCR): {} ({}s, isolated)", "Đã ghép (OCR cache): {} ({} giây, tiến trình riêng)"),
    ("Proton CT2 correction is unavailable in the portable build — correction skipped", "Sửa chính tả Proton CT2 không có trong bản portable — bỏ qua correction"),
    ("Warming correction model...", "Đang khởi động mô hình sửa chính tả..."),
    ("[{}] Using Step 1 OCR cache; preprocess/OCR skipped", "[{}] Dùng OCR cache từ Bước 1; bỏ qua preprocess/OCR"),
    ("[{}] Preprocess geometry before OCR...", "[{}] Đang tiền xử lý hình học trước OCR..."),
    ("[{}] Skip correction: digital PDF uses merged native/OCR KIE JSON", "[{}] Bỏ qua sửa chính tả: PDF số dùng JSON KIE đã gộp chữ gốc/OCR"),
    ("[{}] KIE input: saving completed OCR results to {}", "[{}] Đầu vào KIE: đang lưu kết quả OCR hoàn chỉnh vào {}"),
    ("[{}] KIE: mode={} ready={} selected_pages={}", "[{}] KIE: chế_độ={} sẵn_sàng={} trang_đã_chọn={}"),
    ("Excel written: {}", "Đã ghi Excel: {}"),
    ("[{}] digital merge skipped: source file no longer exists ({}); keeping OCR-backed output", "[{}] Bỏ qua gộp lớp chữ số: file nguồn không còn tồn tại ({}); giữ đầu ra từ OCR"),
    ("[{}] isolated assemble failed ({}); falling back to in-process assemble", "[{}] Ghép ở tiến trình riêng thất bại ({}); chuyển sang ghép trong tiến trình hiện tại"),
    ("Correction model could not be loaded — correction skipped", "Sửa chính tả: không tải được model — bỏ qua correction"),
    ("[{}] Geometry PDF ready: {}", "[{}] PDF hình học đã sẵn sàng: {}"),
    ("[{}] Preprocess failed/empty, using original PDF: {}", "[{}] Tiền xử lý thất bại/rỗng, dùng PDF gốc: {}"),
    ("[{}] assemble failed: {}", "[{}] Ghép thất bại: {}"),
    ("[{}] KIE WARN: 0 field_instances returned. The form will be empty. Model loaded={}, selected_pages={}", "[{}] CẢNH BÁO KIE: trả về 0 field_instances. Biểu mẫu sẽ trống. Model đã tải={}, trang đã chọn={}"),
    ("[{}] KIE: {} field_instances", "[{}] KIE: {} field_instances"),
    ("[{}] KIE failed: {}", "[{}] KIE thất bại: {}"),
    ("Excel write failed: {}", "Ghi Excel thất bại: {}"),
    ("[{}] Digital layer merge page0: {}", "[{}] Gộp lớp chữ số trang 0: {}"),
    ("[{}] correction PDF rewrite failed: {}", "[{}] Ghi lại PDF sau sửa chính tả thất bại: {}"),
    ("[{}] digital layer merge failed: {}", "[{}] Gộp lớp chữ số thất bại: {}"),

    # KIE model lifecycle
    ("LayoutLMv3 ONNX missing: {}", "Thiếu LayoutLMv3 ONNX: {}"),
    ("Loading LayoutLMv3 runtime imports...", "Đang tải thư viện runtime LayoutLMv3..."),
    ("LayoutLMv3 runtime imports ready ({}s)", "Thư viện runtime LayoutLMv3 đã sẵn sàng ({} giây)"),
    ("Loading LayoutLMv3 ONNX int8 ({})...", "Đang tải LayoutLMv3 ONNX int8 ({})..."),
    ("LayoutLMv3 ONNX session ready ({}s)", "Phiên LayoutLMv3 ONNX đã sẵn sàng ({} giây)"),
    ("LayoutLMv3 tokenizer ready ({}s)", "Tokenizer LayoutLMv3 đã sẵn sàng ({} giây)"),
    ("LayoutLMv3 ONNX ready ({} labels, total={}s)", "LayoutLMv3 ONNX đã sẵn sàng ({} nhãn, tổng={} giây)"),
    ("LayoutLMv3 visual model dir missing: {}", "Thiếu thư mục mô hình LayoutLMv3 visual: {}"),
    ("LayoutLMv3 visual ONNX missing: {}", "Thiếu LayoutLMv3 visual ONNX: {}"),
    ("Loading LayoutLMv3 visual runtime imports...", "Đang tải thư viện runtime LayoutLMv3 visual..."),
    ("LayoutLMv3 visual runtime imports ready ({}s)", "Thư viện runtime LayoutLMv3 visual đã sẵn sàng ({} giây)"),
    ("Loading LayoutLMv3 visual ONNX int8 ({})...", "Đang tải LayoutLMv3 visual ONNX int8 ({})..."),
    ("LayoutLMv3 visual ONNX session ready ({}s)", "Phiên LayoutLMv3 visual ONNX đã sẵn sàng ({} giây)"),
    ("LayoutLMv3 visual tokenizer/processor ready ({}s)", "Tokenizer/bộ xử lý LayoutLMv3 visual đã sẵn sàng ({} giây)"),
    ("LayoutLMv3 visual ONNX ready ({} labels, threads={}, total={}s)", "LayoutLMv3 visual ONNX đã sẵn sàng ({} nhãn, luồng={}, tổng={} giây)"),
    ("LayoutLMv3 load failed: {}", "Tải LayoutLMv3 thất bại: {}"),
    ("LayoutLMv3 visual load failed: {}", "Tải LayoutLMv3 visual thất bại: {}"),
    ("KIE model dir not found — fallback to rule-based metadata extractor", "Không tìm thấy thư mục mô hình KIE — chuyển sang bộ trích xuất metadata theo quy tắc"),
    ("Loading LiLT ONNX from {}...", "Đang tải LiLT ONNX từ {}..."),
    ("KIE warmup OK ({} labels)", "Khởi động KIE thành công ({} nhãn)"),
    ("KIE warmup failed: {}", "Khởi động KIE thất bại: {}"),

    # Accuracy measurement
    ("First run: OCRing the sample file to create a comparison baseline...", "Lần đầu chạy: đang OCR file mẫu để làm cơ sở so sánh..."),
    ("Cache saved: {}", "Đã lưu cache: {}"),
    ("Reading ground-truth text (groundtruth.txt when available, otherwise DOCX)...", "Đọc text gốc (groundtruth.txt nếu có, không thì docx)..."),
    ("Obtaining this application's OCR text (runs once, then uses cache)...", "Lấy text OCR của phần mềm này (sẽ chạy lần đầu, cache về sau)..."),
    ("Extracting text from the PDF you provided...", "Trích text từ PDF bạn tải lên..."),
    ("Calculating CER/WER for both results...", "Tính CER/WER cho cả hai phía..."),

    # OCR, downloads, and PDF correction
    ("DOCX-export OCR completed: {}", "OCR để xuất DOCX đã hoàn tất: {}"),
    ("Processing {} pages...", "Đang xử lý {} trang..."),
    ("OCR completed: {}", "OCR đã hoàn tất: {}"),
    ("Assembled (cached OCR): {}", "Đã ghép (OCR cache): {}"),
    ("OCR page {}/{}...", "Đang OCR trang {}/{}..."),
    ("  Page {}: {} lines detected", "  Trang {}: nhận diện {} dòng"),
    ("Parallel OCR completed: {} selected page(s) in {}s ({} workers, max {} queued, {}s/page avg)", "OCR song song hoàn tất: {} trang đã chọn sau {} giây ({} worker, tối đa {} trong hàng đợi, trung bình {} giây/trang)"),
    ("Parallel OCR completed: {} pages in {}s ({} workers, max {} queued, {}s/page avg)", "OCR song song hoàn tất: {} trang sau {} giây ({} worker, tối đa {} trong hàng đợi, trung bình {} giây/trang)"),
    ("Rebuilt PDF with {} corrections", "Đã dựng lại PDF với {} chỗ sửa"),
    ("  Page {}: {} layout regions ({} primary + {} semantic)", "  Trang {}: {} vùng bố cục ({} chính + {} ngữ nghĩa)"),
    ("DOCX export source manifest: {} page(s), source_mode={}", "Danh mục nguồn xuất DOCX: {} trang, chế_độ_nguồn={}"),
    ("Digital PDF detected: extracting native text layer to OCR-compatible JSON...", "Đã nhận diện PDF số: đang trích xuất lớp chữ gốc sang JSON tương thích OCR..."),
    ("  Page {}/{}: {} lines detected", "  Trang {}/{}: nhận diện {} dòng"),
    ("  Page {}/{}: OCR failed", "  Trang {}/{}: OCR thất bại"),
    ("Parallel OCR failed, falling back to serial: {}", "OCR song song thất bại, chuyển sang tuần tự: {}"),
    ("DocLayout-YOLO DocStructBench layout analysis enabled", "Đã bật phân tích bố cục DocLayout-YOLO DocStructBench"),
    ("DocLayout-YOLO DocLayNet semantic analysis enabled", "Đã bật phân tích ngữ nghĩa DocLayout-YOLO DocLayNet"),
    ("  Layout analysis failed: {}", "  Phân tích bố cục thất bại: {}"),
    ("DOCX export: all pages use native text; OCR skipped", "Xuất DOCX: mọi trang dùng chữ gốc; bỏ qua OCR"),
    ("  Page {}/{}: OCR error: {}", "  Trang {}/{}: lỗi OCR: {}"),
    ("Parallel init failed, using serial: {}", "Khởi tạo song song thất bại, dùng tuần tự: {}"),
    ("Parallel OCR: {} page workers for {}/{} OCR page(s)", "OCR song song: {} worker trang cho {}/{} trang cần OCR"),
    ("Parallel init failed, using serial OCR: {}", "Khởi tạo song song thất bại, dùng OCR tuần tự: {}"),
    ("Downloading ScreenAI from Google...", "Đang tải ScreenAI từ Google..."),
    ("Downloading ScreenAI v{} ({} MB)...", "Đang tải ScreenAI v{} ({} MB)..."),
    ("Copying ScreenAI v{} from Chrome...", "Đang sao chép ScreenAI v{} từ Chrome..."),
    ("CRX SHA256 verified OK (Google announced: {}...)", "Đã xác minh CRX SHA256 (Google công bố: {}...)"),
    ("ScreenAI v{} installed: {}", "Đã cài ScreenAI v{}: {}"),
    ("ScreenAI ready: {}", "ScreenAI đã sẵn sàng: {}"),
    ("Copy failed: {}. Will try downloading...", "Sao chép thất bại: {}. Sẽ thử tải xuống..."),
    ("Downloading: {}%", "Đang tải: {}%"),
    ("Digital PDF path: extracting text+bbox from {} pages...", "Luồng PDF số: đang trích xuất chữ+bbox từ {} trang..."),
    ("Digital extraction completed: {}", "Trích xuất PDF số đã hoàn tất: {}"),
    ("Saved companion JSON: {}", "Đã lưu JSON đi kèm: {}"),
    ("Found {} word correction(s):", "Tìm thấy {} chỗ sửa từ:"),
    ("Saved: {}", "Đã lưu: {}"),
    ("No OCR positions JSON found, copying original.", "Không tìm thấy JSON vị trí OCR, đang sao chép bản gốc."),
    ("Warning: failed to sync companion JSON: {}", "Cảnh báo: đồng bộ JSON đi kèm thất bại: {}"),
    ("No differences found. Keeping original PDF and syncing JSON.", "Không tìm thấy khác biệt. Giữ PDF gốc và đồng bộ JSON."),
    ("Processing page {}...", "Đang xử lý trang {}..."),
    ("Byte-level replacement found 0 matches, trying rebuild...", "Thay thế mức byte không tìm thấy kết quả, đang thử dựng lại..."),
    ("Rebuild fallback failed: {}", "Dựng lại dự phòng thất bại: {}"),
    ("  Modified {} occurrences in stream", "  Đã sửa {} vị trí trong stream"),
    ("  Warning: Could not process stream: {}", "  Cảnh báo: không xử lý được stream: {}"),

    # Pipeline and repository maintenance
    ("[pipeline] feeder_loop crashed: {}\n{}", "[quy trình] feeder_loop bị lỗi: {}\n{}"),
    ("[pipeline] collector_loop crashed: {}\n{}", "[quy trình] collector_loop bị lỗi: {}\n{}"),
    ("[pipeline] correction_loop crashed: {}\n{}", "[quy trình] correction_loop bị lỗi: {}\n{}"),
    ("[pipeline] [{}] correction crashed: {}\n{}", "[quy trình] [{}] sửa chính tả bị lỗi: {}\n{}"),
    ("[pipeline] kie_loop crashed: {}\n{}", "[quy trình] kie_loop bị lỗi: {}\n{}"),
    ("[pipeline] [{}] KIE crashed: {}\n{}", "[quy trình] [{}] KIE bị lỗi: {}\n{}"),
    ("Startup repair done: {}", "Sửa chữa lúc khởi động hoàn tất: {}"),
    ("running schema converter v{} -> v{}", "đang chạy bộ chuyển schema v{} -> v{}"),
    ("schema migration complete: {} -> {}", "migration schema hoàn tất: {} -> {}"),
)


UI_LOG_TEXT_PAIRS += UI_BACKEND_LOG_TEXT_PAIRS


# Verbose PDF-to-DOCX/table diagnostics are visible when the activity log's
# detailed mode is enabled, so they are localized as well.
UI_TABLE_LOG_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    ("docling_tableformer structure recognizer found {} tables", "Bộ nhận diện cấu trúc docling_tableformer tìm thấy {} bảng"),
    ("docling_tableformer crop failed on page {}: {}", "Cắt vùng cho docling_tableformer thất bại ở trang {}: {}"),
    ("docling_tableformer_v1_onnx structure recognizer found {} tables", "Bộ nhận diện cấu trúc docling_tableformer_v1_onnx tìm thấy {} bảng"),
    ("docling_tableformer_v1_onnx crop failed on page {}: {}", "Cắt vùng cho docling_tableformer_v1_onnx thất bại ở trang {}: {}"),
    ("docling_tableformer_v2_onnx structure recognizer found {} tables", "Bộ nhận diện cấu trúc docling_tableformer_v2_onnx tìm thấy {} bảng"),
    ("docling_tableformer_v2_onnx crop failed on page {}: {}", "Cắt vùng cho docling_tableformer_v2_onnx thất bại ở trang {}: {}"),
    ("docling_tableformer_v2_torch structure recognizer found {} tables", "Bộ nhận diện cấu trúc docling_tableformer_v2_torch tìm thấy {} bảng"),
    ("docling_tableformer_v2_torch crop failed on page {}: {}", "Cắt vùng cho docling_tableformer_v2_torch thất bại ở trang {}: {}"),
    ("Using companion OCR JSON text source: {} lines", "Đang dùng nguồn chữ từ JSON OCR đi kèm: {} dòng"),
    ("PDF: {} pages, {} text lines extracted", "PDF: {} trang, đã trích xuất {} dòng chữ"),
    ("Merged {} lines into {} paragraphs", "Đã gộp {} dòng thành {} đoạn văn"),
    ("Loaded {} table structures from canonical cache", "Đã tải {} cấu trúc bảng từ cache canonical"),
    ("Regridded page-local table on page {}: {}x{} -> {}x{}", "Đã chia lại lưới bảng cục bộ ở trang {}: {}x{} -> {}x{}"),
    ("  Page {}: Selected {} by quality score ({})", "  Trang {}: đã chọn {} theo điểm chất lượng ({})"),
    ("Running Hybrid Table Detection (GMFT-ONNX + Img2Table + RapidTable ensemble)...", "Đang nhận diện bảng kết hợp (GMFT-ONNX + Img2Table + RapidTable)..."),
    ("  Page {}: Selected docling_tableformer by Docling-first selector ({})", "  Trang {}: đã chọn docling_tableformer bằng bộ chọn ưu tiên Docling ({})"),
    ("Running DocLayout-anchored tables (DocLayout bbox + GMFT-ONNX + Docling TableFormer v1 ONNX)...", "Đang xử lý bảng neo theo DocLayout (bbox DocLayout + GMFT-ONNX + Docling TableFormer v1 ONNX)..."),
    ("DocLayout table pipeline: selected {} tables", "Quy trình bảng DocLayout: đã chọn {} bảng"),
    ("Running DocLayout-anchored tables (DocLayout bbox + RapidTable SLANet+ primary)...", "Đang xử lý bảng neo theo DocLayout (bbox DocLayout + RapidTable SLANet+ chính)..."),
    ("  Added table: {}x{}", "  Đã thêm bảng: {}x{}"),
    ("PDF to DOCX Position-Preserving Converter v4", "Bộ chuyển PDF sang DOCX giữ nguyên vị trí v4"),
    ("PDF: {}", "PDF: {}"),
    ("Output: {}", "Đầu ra: {}"),
    ("Refined figure layout regions: dropped={}, trimmed={}", "Đã tinh chỉnh vùng bố cục hình: loại={}, cắt={}"),
    ("Removed {} OCR line(s) inside rendered figure regions", "Đã xóa {} dòng OCR trong vùng hình được dựng"),
    ("Enriched {}/{} lines with Screen AI metadata", "Đã bổ sung metadata Screen AI cho {}/{} dòng"),
    ("PDF: {} pages, {} OCR JSON text lines loaded", "PDF: {} trang, đã tải {} dòng chữ từ JSON OCR"),
    ("Paragraph edge: {} split={} merge={} reasons={}", "Biên đoạn văn: {} tách={} gộp={} lý_do={}"),
    ("Healed {} OCR paragraph fragments across block/page boundaries", "Đã nối {} mảnh đoạn văn OCR qua ranh giới khối/trang"),
    ("Removed {} page number lines", "Đã xóa {} dòng số trang"),
    ("Detected dual-column footer on page {}: {}L + {}R lines", "Đã nhận diện chân trang hai cột ở trang {}: {} dòng trái + {} dòng phải"),
    ("Detected {} footnote lines (avg font: {})", "Đã nhận diện {} dòng chú thích chân trang (font trung bình: {})"),
    ("Page {} Margins: Left={}, Right={} (RobustMax={})", "Lề trang {}: trái={}, phải={} (RobustMax={})"),
    ("Removed {} repeated article running header/footer line(s)", "Đã xóa {} dòng đầu/chân trang lặp của bài viết"),
    ("Split {} OCR line(s) crossing detected multi-column gutters", "Đã tách {} dòng OCR đi qua rãnh đa cột đã nhận diện"),
    ("Split {} digital dual-header line(s) by span geometry", "Đã tách {} dòng đầu trang số hai phần theo hình học span"),
    ("Removed {} publication running header/footer line(s)", "Đã xóa {} dòng đầu/chân trang lặp của ấn phẩm"),
    ("DocLayout on-demand analysis skipped: ONNX model/runtime unavailable", "Bỏ qua phân tích DocLayout theo yêu cầu: không có mô hình/runtime ONNX"),
    ("DocLayout on-demand analysis found {} regions on {} pages", "Phân tích DocLayout theo yêu cầu tìm thấy {} vùng trên {} trang"),
    ("Updated canonical OCR sidecar with layout regions: {}", "Đã cập nhật các vùng bố cục vào sidecar OCR canonical: {}"),
    ("Table cache missing; regenerating", "Thiếu cache bảng; đang tạo lại"),
    ("Table cache invalid (page visual fingerprint mismatch); regenerating", "Cache bảng không hợp lệ (dấu vân tay hình ảnh trang không khớp); đang tạo lại"),
    ("Table cache invalid (page OCR text hash mismatch); regenerating", "Cache bảng không hợp lệ (hash chữ OCR trang không khớp); đang tạo lại"),
    ("Table cache invalid (status is not complete); regenerating", "Cache bảng không hợp lệ (trạng thái chưa hoàn tất); đang tạo lại"),
    ("Table cache entry {} has no usable cell bboxes; regenerating", "Mục cache bảng {} không có bbox ô dùng được; đang tạo lại"),
    ("Table cache missing table_structures; regenerating", "Cache bảng thiếu table_structures; đang tạo lại"),
    ("Updated canonical OCR sidecar with table structures: {}", "Đã cập nhật cấu trúc bảng vào sidecar OCR canonical: {}"),
    ("Repaired {} table-boundary continuation fragment(s)", "Đã sửa {} mảnh tiếp nối ở ranh giới bảng"),
    ("Assigned {} OCR table lines by geometry cell mapping", "Đã gán {} dòng bảng OCR theo ánh xạ hình học ô"),
    ("Preserved {} non-table fragment(s) from OCR lines crossing table boundaries", "Đã giữ {} mảnh không thuộc bảng từ các dòng OCR đi qua ranh giới bảng"),
    ("Applied line-consensus table assignment to {} boundary line(s)", "Đã áp dụng gán bảng theo đồng thuận dòng cho {} dòng ranh giới"),
    ("Assigned {} OCR table lines by geometry-overlap fallback", "Đã gán {} dòng bảng OCR bằng dự phòng chồng lấn hình học"),
    ("Repaired split header fragments in {} table(s)", "Đã sửa các mảnh tiêu đề bị tách trong {} bảng"),
    ("Added {} narrow trailing table column(s) from layout grid", "Đã thêm {} cột bảng hẹp ở cuối từ lưới bố cục"),
    ("Added {} trailing blank table row(s) from layout grid", "Đã thêm {} hàng bảng trống ở cuối từ lưới bố cục"),
    ("Added {} grouped-header grid column(s)", "Đã thêm {} cột lưới tiêu đề nhóm"),
    ("Normalized {} grouped table header row(s)", "Đã chuẩn hóa {} hàng tiêu đề bảng nhóm"),
    ("Repaired wrapped continuation token(s) in {} grouped table header(s)", "Đã sửa token tiếp nối xuống dòng trong {} tiêu đề bảng nhóm"),
    ("Added {} page-local fallback table segment(s)", "Đã thêm {} đoạn bảng dự phòng cục bộ theo trang"),
    ("Stabilized {} page-local table grid(s) from adjacent page schemas", "Đã ổn định {} lưới bảng cục bộ theo trang từ schema trang liền kề"),
    ("Trimmed {} empty trailing table column(s)", "Đã cắt {} cột bảng trống ở cuối"),
    ("Stabilized {} continuation table schema(s) from previous page geometry", "Đã ổn định {} schema bảng tiếp nối từ hình học trang trước"),
    ("Repaired {} OCR-anchored table row gap(s)", "Đã sửa {} khoảng trống hàng bảng neo theo OCR"),
    ("Inserted {} OCR-anchored missing table row(s)", "Đã chèn {} hàng bảng thiếu neo theo OCR"),
    ("Repaired {} shifted leading table cell(s)", "Đã sửa {} ô đầu bảng bị lệch"),
    ("Fused {} page-local continuation table row(s)", "Đã hợp nhất {} hàng bảng tiếp nối cục bộ theo trang"),
    ("Suppressed {} repeated leading table cell pair(s)", "Đã loại {} cặp ô đầu bảng lặp"),
    ("Normalized {} section heading row span(s)", "Đã chuẩn hóa {} span hàng tiêu đề mục"),
    ("Inferred {} missing section marker(s)", "Đã suy ra {} dấu mục bị thiếu"),
    ("Stabilized {} continued table segment column schema(s)", "Đã ổn định {} schema cột của đoạn bảng tiếp nối"),
    ("Composed {} continued table group(s) for Word flow", "Đã ghép {} nhóm bảng tiếp nối cho luồng Word"),
    ("Removed {} false-positive 1-column table(s)", "Đã xóa {} bảng một cột nhận diện nhầm"),
    ("Split {} stacked table(s)", "Đã tách {} bảng xếp chồng"),
    ("img2table not available, skipping table detection", "Không có img2table, bỏ qua nhận diện bảng"),
    ("  img2table: Starting extraction (this may take time for large files)...", "  img2table: đang bắt đầu trích xuất (file lớn có thể mất thời gian)..."),
    ("Hybrid: GMFT-ONNX not available", "Kết hợp: không có GMFT-ONNX"),
    ("Hybrid: legacy PyTorch GMFT not enabled", "Kết hợp: chưa bật GMFT PyTorch cũ"),
    ("  Page {}: Selected gmft_onnx_layout by GMFT+Docling selector ({}; {})", "  Trang {}: đã chọn gmft_onnx_layout bằng bộ chọn GMFT+Docling ({}; {})"),
    ("RapidTable primary pipeline: RapidTable SLANet+ not available", "Quy trình RapidTable chính: không có RapidTable SLANet+"),
    ("RapidTable primary pipeline: selected {} tables", "Quy trình RapidTable chính: đã chọn {} bảng"),
    ("Combined table engines: kept {} native table(s), {} model table(s), skipped {} overlap(s)", "Kết hợp bộ máy bảng: giữ {} bảng gốc, {} bảng mô hình, bỏ qua {} vùng chồng lấn"),
    ("PyMuPDF native table extractor: selected {} tables with native cell text", "Bộ trích xuất bảng gốc PyMuPDF: đã chọn {} bảng có chữ ô gốc"),
    ("PyMuPDF native table extractor: no tables found", "Bộ trích xuất bảng gốc PyMuPDF: không tìm thấy bảng"),
    ("DocLayout GMFT + Docling TableFormer v1 ONNX produced no tables; no alternate table fallback is enabled", "DocLayout GMFT + Docling TableFormer v1 ONNX không tạo được bảng; chưa bật phương án bảng dự phòng khác"),
    ("Digital PDF exported through pdf2docx native converter", "Đã xuất PDF số bằng bộ chuyển đổi gốc pdf2docx"),
    ("SUMMARY", "TỔNG KẾT"),
    ("Text lines: {}", "Dòng chữ: {}"),
    ("Tables: {}", "Bảng: {}"),
    ("Could not load OCR JSON for {}: {}", "Không tải được JSON OCR cho {}: {}"),
    ("Detected dual-column header on page {}: {}L + {}R lines", "Đã nhận diện đầu trang hai cột ở trang {}: {} dòng trái + {} dòng phải"),
    ("DEBUG FN CHECK: '{}...'", "KIỂM TRA DEBUG FN: '{}...'"),
    ("  Global Avg Font: {}", "  Font trung bình toàn cục: {}"),
    ("  Line Font: {} ({}%)", "  Font dòng: {} ({}%)"),
    ("  Is Small (<88%): {}", "  Là chữ nhỏ (<88%): {}"),
    ("  Score: {}", "  Điểm: {}"),
    ("DocLayout on-demand analysis unavailable: {}", "Không có phân tích DocLayout theo yêu cầu: {}"),
    ("DocLayout on-demand init failed: {}", "Khởi tạo DocLayout theo yêu cầu thất bại: {}"),
    ("DocLayout on-demand analysis failed: {}", "Phân tích DocLayout theo yêu cầu thất bại: {}"),
    ("Could not update canonical OCR sidecar with layout regions: {}", "Không cập nhật được vùng bố cục vào sidecar OCR canonical: {}"),
    ("Table cache invalid ({} mismatch); regenerating", "Cache bảng không hợp lệ ({} không khớp); đang tạo lại"),
    ("Loaded empty table structure cache from canonical sidecar", "Đã tải cache cấu trúc bảng rỗng từ sidecar canonical"),
    ("Could not update canonical OCR sidecar with table structures: {}", "Không cập nhật được cấu trúc bảng vào sidecar OCR canonical: {}"),
    ("img2table error: {}", "Lỗi img2table: {}"),
    ("Hybrid: Img2Table not available", "Kết hợp: không có Img2Table"),
    ("Hybrid: RapidTable SLANet+ not available", "Kết hợp: không có RapidTable SLANet+"),
    ("Hybrid: RapidTable SLANet+ skipped because layout table boxes are unavailable", "Kết hợp: bỏ qua RapidTable SLANet+ vì không có bbox bảng từ bố cục"),
    ("Hybrid: Starting RapidTable SLANet+ thread...", "Kết hợp: đang khởi chạy luồng RapidTable SLANet+..."),
    ("Hybrid: RapidTable SLANet+ thread finished. Found {} tables.", "Kết hợp: luồng RapidTable SLANet+ đã xong. Tìm thấy {} bảng."),
    ("DocLayout table pipeline: GMFT-ONNX structure recognizer not available", "Quy trình bảng DocLayout: không có bộ nhận diện cấu trúc GMFT-ONNX"),
    ("DocLayout table pipeline: Starting GMFT-ONNX structure recognizer...", "Quy trình bảng DocLayout: đang chạy bộ nhận diện cấu trúc GMFT-ONNX..."),
    ("DocLayout table pipeline: GMFT-ONNX finished. Found {} tables.", "Quy trình bảng DocLayout: GMFT-ONNX đã xong. Tìm thấy {} bảng."),
    ("DocLayout table pipeline: Docling TableFormer v1 ONNX not available", "Quy trình bảng DocLayout: không có Docling TableFormer v1 ONNX"),
    ("DocLayout table pipeline: Starting Docling TableFormer v1 ONNX...", "Quy trình bảng DocLayout: đang chạy Docling TableFormer v1 ONNX..."),
    ("DocLayout table pipeline: Docling TableFormer v1 ONNX finished. Found {} tables.", "Quy trình bảng DocLayout: Docling TableFormer v1 ONNX đã xong. Tìm thấy {} bảng."),
    ("RapidTable primary pipeline failed: {}", "Quy trình RapidTable chính thất bại: {}"),
    ("PyMuPDF native table extraction failed: {}", "Trích xuất bảng gốc bằng PyMuPDF thất bại: {}"),
    ("  Suppressed {} leading continuation border span(s)", "  Đã loại {} span đường viền tiếp nối đầu"),
    ("  Refined Table {}: Force-split {} rows at x={}", "  Đã tinh chỉnh bảng {}: buộc tách {} hàng tại x={}"),
    ("Native PDF source-mode inference skipped: {}", "Bỏ qua suy luận chế độ nguồn PDF gốc: {}"),
    ("Warning: backfill could not read PDF text: {}", "Cảnh báo: backfill không đọc được chữ PDF: {}"),
    ("Warning: backfill could not open DOCX: {}", "Cảnh báo: backfill không mở được DOCX: {}"),
    ("Warning: backfill could not read native words: {}", "Cảnh báo: backfill không đọc được các từ gốc: {}"),
    ("Warning: backfill could not read document.xml: {}", "Cảnh báo: backfill không đọc được document.xml: {}"),
    ("Backfilled {} missing native token(s) into DOCX", "Đã backfill {} token gốc bị thiếu vào DOCX"),
    ("Warning: backfill DOCX patch failed: {}", "Cảnh báo: vá DOCX bằng backfill thất bại: {}"),
    ("pdf2docx unavailable for digital PDF export: {}", "Không có pdf2docx để xuất PDF số: {}"),
    ("pdf2docx native export failed: {}", "Xuất gốc bằng pdf2docx thất bại: {}"),
    ("Sanitized {} pdf2docx OOXML size value(s)", "Đã làm sạch {} giá trị kích thước OOXML của pdf2docx"),
    ("Warning: Failed to infer visual spaces from PDF: {}", "Cảnh báo: không suy ra được khoảng trắng trực quan từ PDF: {}"),
    ("Repaired pdf2docx visual spaces in {} text node(s)", "Đã sửa khoảng trắng trực quan pdf2docx trong {} nút chữ"),
    ("Warning: Failed to set DOCX properties: {}", "Cảnh báo: đặt thuộc tính DOCX thất bại: {}"),
    ("Export mode: pdf2docx native digital PDF", "Chế độ xuất: PDF số gốc bằng pdf2docx"),
    ("Skipped {} unresolved table-overlap lines after table mapping", "Đã bỏ qua {} dòng chồng lấn bảng chưa giải quyết sau ánh xạ bảng"),
    ("Kept {} non-table text fragment(s) from table-crossing OCR lines", "Đã giữ {} mảnh chữ không thuộc bảng từ các dòng OCR đi qua bảng"),
    ("ERROR: {}", "LỖI: {}"),
)


UI_LOG_TEXT_PAIRS += UI_TABLE_LOG_TEXT_PAIRS


UI_TABLE_EXTRA_LOG_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    ("  img2table (Hybrid Mode): p{} Table {} {}x{} @ y={}-{}", "  img2table (chế độ kết hợp): trang {} bảng {} {}x{} @ y={}-{}"),
    ("Hybrid: Starting GMFT-ONNX thread...", "Kết hợp: đang khởi chạy luồng GMFT-ONNX..."),
    ("Hybrid: GMFT-ONNX thread finished. Found {} tables.", "Kết hợp: luồng GMFT-ONNX đã xong. Tìm thấy {} bảng."),
    ("Hybrid: Starting legacy PyTorch GMFT thread...", "Kết hợp: đang khởi chạy luồng GMFT PyTorch cũ..."),
    ("Hybrid: legacy PyTorch GMFT thread finished. Found {} tables.", "Kết hợp: luồng GMFT PyTorch cũ đã xong. Tìm thấy {} bảng."),
    ("Hybrid: Starting Img2Table thread...", "Kết hợp: đang khởi chạy luồng Img2Table..."),
    ("Hybrid: Img2Table thread finished. Found {} tables.", "Kết hợp: luồng Img2Table đã xong. Tìm thấy {} bảng."),
    ("Hybrid: RapidTable SLANet+ failed: {}", "Kết hợp: RapidTable SLANet+ thất bại: {}"),
    ("DocLayout table pipeline: GMFT-ONNX failed: {}", "Quy trình bảng DocLayout: GMFT-ONNX thất bại: {}"),
    ("DocLayout table pipeline: Docling TableFormer v1 ONNX failed: {}", "Quy trình bảng DocLayout: Docling TableFormer v1 ONNX thất bại: {}"),
    ("  Leading border suppression failed at r{}-{}c{}: {}", "  Loại đường viền đầu thất bại tại hàng {}-{} cột {}: {}"),
    ("Warning: backfill native text into DOCX failed: {}", "Cảnh báo: backfill chữ gốc vào DOCX thất bại: {}"),
    ("Loaded layout regions for {} pages", "Đã tải vùng bố cục cho {} trang"),
    ("Tagged {}/{} lines with semantic types", "Đã gắn loại ngữ nghĩa cho {}/{} dòng"),
    ("Figure extraction source: {}", "Nguồn trích xuất hình: {}"),
    ("Inserted page break before source page {}", "Đã chèn ngắt trang trước trang nguồn {}"),
    ("  img2table: Page {} is too large (~{}MP). Skipping img2table to prevent hang.", "  img2table: trang {} quá lớn (~{}MP). Bỏ qua img2table để tránh treo."),
    ("Hybrid: GMFT-ONNX failed: {}", "Kết hợp: GMFT-ONNX thất bại: {}"),
    ("Hybrid: legacy PyTorch GMFT failed: {}", "Kết hợp: GMFT PyTorch cũ thất bại: {}"),
    ("Hybrid: Img2Table failed: {}", "Kết hợp: Img2Table thất bại: {}"),
    ("  Merged {} cells at r{}c{} (Text: '{}')", "  Đã gộp {} ô tại hàng {} cột {} (chữ: '{}')"),
    ("Warning: Failed to set DOCX properties after pdf2docx export: {}", "Cảnh báo: đặt thuộc tính DOCX sau khi xuất bằng pdf2docx thất bại: {}"),
    ("layout_analyzer not available, skipping semantic tagging", "Không có layout_analyzer, bỏ qua gắn nhãn ngữ nghĩa"),
    ("Semantic tagging failed: {}", "Gắn nhãn ngữ nghĩa thất bại: {}"),
    ("Native table extraction found no candidate tables; model table pipeline may be used", "Trích xuất bảng gốc không tìm thấy bảng ứng viên; có thể dùng quy trình bảng bằng mô hình"),
    ("Figure source PDF open failed: {}", "Mở PDF nguồn hình thất bại: {}"),
    ("Page {}: switched to {}", "Trang {}: đã chuyển sang {}"),
    ("  Warning: Could not extract cell data for p{} t{}: {}", "  Cảnh báo: không trích xuất được dữ liệu ô cho trang {} bảng {}: {}"),
    ("  Merge failed at r{}c{}: {}", "  Gộp thất bại tại hàng {} cột {}: {}"),
    ("  Vertical merge {} cells at r{}c{} (Text: '{}')", "  Gộp dọc {} ô tại hàng {} cột {} (chữ: '{}')"),
    ("V2 table postprocess failed, keeping V1 cells: {}", "Hậu xử lý bảng V2 thất bại, giữ các ô V1: {}"),
    ("  Vertical merge failed at r{}c{}: {}", "  Gộp dọc thất bại tại hàng {} cột {}: {}"),
    ("PyMuPDF native table finder failed on page {}: {}", "Bộ tìm bảng gốc PyMuPDF thất bại ở trang {}: {}"),
    ("  Added figure from page {} (top_bottom)", "  Đã thêm hình từ trang {} (trên_dưới)"),
    ("  Figure extraction failed: {}", "  Trích xuất hình thất bại: {}"),
    ("    Table {}: {}x{} @ y={}-{} [{}]", "    Bảng {}: {}x{} @ y={}-{} [{}]"),
    ("gmft_onnx: Total {} tables extracted", "gmft_onnx: đã trích xuất tổng cộng {} bảng"),
    ("gmft_onnx/layout: Total {} tables extracted", "gmft_onnx/layout: đã trích xuất tổng cộng {} bảng"),
    ("    Table {}: grid refinement {}x{}", "    Bảng {}: tinh chỉnh lưới {}x{}"),
    ("    Table {}: no row/column structure, skipping", "    Bảng {}: không có cấu trúc hàng/cột, bỏ qua"),
    ("gmft_onnx not available, skipping table detection", "Không có gmft_onnx, bỏ qua nhận diện bảng"),
    ("gmft_onnx not available, skipping layout-anchored structure recognition", "Không có gmft_onnx, bỏ qua nhận diện cấu trúc neo theo bố cục"),
    ("  gmft_onnx: Page {} - {} tables detected", "  gmft_onnx: trang {} - nhận diện {} bảng"),
    ("  gmft_onnx/layout: Page {} - {} DocLayout table boxes", "  gmft_onnx/layout: trang {} - {} bbox bảng DocLayout"),
    ("    Table {}: gmft_onnx/layout failed: {}", "    Bảng {}: gmft_onnx/layout thất bại: {}"),
    ("V2 cell matcher: assigned={}/{} orphan={} weak={}", "Bộ khớp ô V2: đã_gán={}/{} rời={} yếu={}"),
    ("V2 cell matcher: repaired {} boundary continuation fragment(s)", "Bộ khớp ô V2: đã sửa {} mảnh tiếp nối ở ranh giới"),
    ("{} structure recognizer found {} tables", "Bộ nhận diện cấu trúc {} tìm thấy {} bảng"),
    ("{} crop failed on page {}: {}", "Cắt vùng {} thất bại ở trang {}: {}"),
)


UI_LOG_TEXT_PAIRS += UI_TABLE_EXTRA_LOG_TEXT_PAIRS
