"""English/Vietnamese pairs for legacy UI source strings.

The application originally mixed keyed translations with Vietnamese source
text embedded directly in PySide widgets.  Rewriting every large screen at
once would make the UI unnecessarily fragile, so the localization layer also
supports a gettext-style source catalog: either language can be the source,
and :func:`scanindex.infra.translations.localize_text` selects the requested
variant.

Placeholders are positional for matching purposes.  ``{}``, ``{name}``, and
``{0}`` are treated alike by the matcher; values are copied to the translated
template from left to right.
"""

UI_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    # Qt/common actions and messages
    ("Accept", "Đồng ý"),
    ("Add", "Thêm"),
    ("Apply", "Áp dụng"),
    ("Back", "Quay lại"),
    ("Cancel", "Hủy"),
    ("Delete", "Xóa"),
    ("Clear", "Xóa"),
    ("Discard", "Không lưu"),
    ("Close", "Đóng"),
    ("Confirm", "Xác nhận"),
    ("Error", "Lỗi"),
    ("Information", "Thông báo"),
    ("No", "Không"),
    ("None", "Không có"),
    ("OK", "Đồng ý"),
    ("Open", "Mở"),
    ("Remove", "Xóa"),
    ("Reset", "Đặt lại"),
    ("Restore defaults", "Khôi phục mặc định"),
    ("Retry", "Thử lại"),
    ("Save", "Lưu"),
    ("Search", "Tìm"),
    ("Stop", "Dừng"),
    ("Warning", "Cảnh báo"),
    ("Yes", "Có"),
    ("Ready", "Sẵn sàng"),
    ("Not started", "Chưa chạy"),
    ("Not saved", "Chưa lưu"),
    ("No results.", "Không có kết quả."),
    ("No repository configured", "Chưa có kho"),
    ("Info", "Thông tin"),
    ("0 file", "0 file"),
    ("{} file", "{} file"),
    ("0.0s", "0.0s"),
    ("{}s", "{}s"),
    ("dd/mm/yyyy", "dd/mm/yyyy"),
    ("Example: 1", "VD: 1"),
    ("PDF (*.pdf)", "PDF (*.pdf)"),
    ("PDF Files (*.pdf)", "PDF Files (*.pdf)"),
    ("ZIP Files (*.zip)", "ZIP Files (*.zip)"),
    (
        "Documents (*.pdf *.png *.bmp *.jpeg *.jpg *.tif *.tiff);;PDF Files (*.pdf);;Image Files (*.png *.bmp *.jpeg *.jpg *.tif *.tiff)",
        "Tài liệu (*.pdf *.png *.bmp *.jpeg *.jpg *.tif *.tiff);;PDF (*.pdf);;Ảnh (*.png *.bmp *.jpeg *.jpg *.tif *.tiff)",
    ),
    ("File", "File"),
    ("Page", "Trang"),
    ("Status", "Trạng thái"),
    ("Notes", "Ghi chú"),
    ("Confidentiality", "Độ mật"),
    ("Mode", "Chế độ"),
    ("Document type", "Loại VB"),
    ("Default", "Mặc định"),
    ("Permanent", "Vĩnh viễn"),
    ("Normal", "Bình thường"),
    ("Good", "Tốt"),
    ("Damaged", "Hỏng"),

    # Startup, navigation, and home
    ("Initializing interface...", "Đang khởi tạo giao diện..."),
    ("Preparing the main screen...", "Đang chuẩn bị màn hình chính..."),
    ("Preparing...", "Đang chuẩn bị..."),
    ("Starting library loading...", "Khởi động tải thư viện..."),
    ("Loading libraries", "Loading thư viện"),
    ("Loading", "Đang tải"),
    ("Releasing", "Đang giải phóng"),
    ("ScreenAI OCR engine", "Bộ máy OCR ScreenAI"),
    ("Proton CT2 correction model", "Mô hình sửa văn bản Proton CT2"),
    ("GMFT + Docling table extraction models", "Các mô hình trích xuất bảng GMFT + Docling"),
    ("KIE inference (LayoutLMv3)", "Suy luận KIE (LayoutLMv3)"),
    ("LightGBM splitter", "Bộ tách LightGBM"),
    ("Loading LightGBM splitter...", "Đang tải bộ tách LightGBM..."),
    ("Done (Export Failed)", "Xong (Xuất thất bại)"),
    ("(Could not read original)", "(Không đọc được bản gốc)"),
    ("Add document — Enter information", "Thêm văn bản — Nhập thông tin"),
    ("Extracted <b>{}</b> passages from the PDF. Enter the metadata below, then click Save.", "Đã trích xuất <b>{}</b> đoạn từ PDF. Điền thông tin metadata bên dưới rồi bấm Lưu."),
    ("Issuing authority *", "Cơ quan ban hành *"),
    ("Subject *", "Trích yếu *"),
    ("Circulation instructions", "Hình thức lưu hành"),
    ("Regime header", "Header chế độ"),
    ("Date", "Ngày tháng"),
    ("Urgency", "Độ khẩn"),
    ("PDF VIEWER", "TRÌNH XEM PDF"),
    ("Select a KIE field, then click words in the PDF to assign/remove them", "Chọn trường KIE → click từ trên PDF để gán/bỏ"),
    ("Select a KIE field to view details", "Chọn một trường KIE để xem chi tiết"),
    ("Choose a function to begin", "Chọn chức năng để bắt đầu"),
    ("Scan PDF → Word", "Chuyển scan PDF → Word"),
    (
        "OCR scanned PDFs, correct Vietnamese spelling, and export DOCX files with tables and images.",
        "OCR file PDF scan, sửa lỗi chính tả tiếng Việt, xuất ra DOCX có bảng biểu và hình ảnh.",
    ),
    ("Archival digitization", "Số hóa lưu trữ"),
    (
        "OCR a folder and extract administrative-document metadata for archival storage.",
        "OCR cả thư mục, trích xuất metadata văn bản hành chính cho lưu trữ.",
    ),
    ("Repository", "Kho lưu trữ"),
    (
        "Search metadata and full text in the digitized PDF repository and filter by HSLTCQ metadata.",
        "Tra cứu metadata và toàn văn kho PDF đã số hóa, lọc theo metadata HSLTCQ.",
    ),
    ("Tools", "Công cụ"),
    ("Measure OCR accuracy and detect classified files in a folder.", "Đo độ chính xác OCR, phát hiện file mật trong thư mục."),
    ("Settings", "Cấu hình"),
    ("Adjust processing speed, models, language, and advanced options.", "Tùy chỉnh tốc độ xử lý, model, ngôn ngữ và tùy chọn nâng cao."),
    ("About", "Giới thiệu"),
    ("Version, usage scope, features, and technology information.", "Thông tin phiên bản, phạm vi sử dụng, chức năng và công nghệ."),
    ("←  Back", "←  Quay lại"),
    ("Preparing: Scan PDF → Word", "Đang chuẩn bị: Chuyển scan PDF → Word"),
    ("Preparing: Archival digitization", "Đang chuẩn bị: Số hóa lưu trữ"),
    ("Opening Repository", "Đang mở Kho lưu trữ"),
    ("Preparing: Tools", "Đang chuẩn bị: Công cụ"),
    ("Preparing: Settings", "Đang chuẩn bị: Cấu hình"),
    ("Preparing: About", "Đang chuẩn bị: Giới thiệu"),
    ("Select PDF or Image Files", "Chọn file PDF hoặc ảnh"),
    ("Please select an input folder.", "Vui lòng chọn thư mục đầu vào."),
    ("No PDF files found.", "Không tìm thấy file PDF."),
    ("Folder not found: {}", "Không tìm thấy thư mục: {}"),
    ("Could not open folder: {}\n{}", "Không mở được thư mục: {}\n{}"),
    ("Failed to read PDF text: {}", "Không đọc được nội dung PDF: {}"),
    ("Invalid file index", "Chỉ số file không hợp lệ"),
    ("Source PDF not found", "Không tìm thấy PDF nguồn"),
    ("Failed to save corrected PDF: {}", "Không lưu được PDF đã sửa: {}"),
    ("Cancel running task", "Xác nhận dừng"),
    ("A task is running. Stop it?", "Đang có tác vụ chạy. Dừng lại?"),
    (
        "The current task will be cancelled and its temporary files will be deleted.",
        "Tác vụ hiện tại sẽ bị hủy và các file tạm sẽ bị xóa.",
    ),
    ("The current task will be asked to cancel.", "Tác vụ hiện tại sẽ được yêu cầu hủy."),
    ("Some supporting tools", "Một số công cụ hỗ trợ"),
    ("OCR accuracy", "Đo độ chính xác OCR"),
    ("Compare an OCR PDF with ground truth using CER/WER.", "So sánh PDF OCR với ground truth bằng CER/WER."),
    ("Detect classified files in a folder", "Phát hiện file mật trong thư mục"),
    (
        "Scan PDF, image, and Word files for MẬT, TỐI MẬT, and TUYỆT MẬT markings.",
        "Quét PDF, ảnh và Word để tìm dấu MẬT, TỐI MẬT, TUYỆT MẬT.",
    ),
    ("Bulk digital signing", "Ký số hàng loạt"),
    (
        "Bulk-sign PDFs: choose input and output folders, then start.",
        "Ký số hàng loạt PDF: chọn thư mục vào, thư mục ra rồi bắt đầu.",
    ),

    # Settings
    ("Technical settings", "Thông số kỹ thuật"),
    ("Catalogs", "Danh mục"),
    ("Language", "Ngôn ngữ"),
    ("Parallel OCR pages", "Số trang OCR song song"),
    ("KIE mode", "Chế độ KIE"),
    ("Repository data", "Dữ liệu Kho lưu trữ"),
    (
        "Resetting repository data deletes all dossiers, PDFs, search indexes, and the current repository database.",
        "Reset dữ liệu kho sẽ xóa toàn bộ hồ sơ, PDF, chỉ mục tìm kiếm và cơ sở dữ liệu trong Kho hiện tại.",
    ),
    ("Reset repository data", "Reset dữ liệu kho"),
    (
        "Select a catalog on the left, then add or remove values on the right.",
        "Chọn một danh mục ở bên trái, sau đó thêm hoặc xóa giá trị ở bên phải.",
    ),
    ("Catalog name", "Tên danh mục"),
    ("New catalog", "Danh mục mới"),
    ("Value", "Giá trị"),
    ("New value", "Giá trị mới"),
    ("Values for: {}", "Giá trị của: {}"),
    ("Document categories", "Thể loại văn bản"),
    ("Party document", "Văn bản Đảng"),
    ("State document", "Văn bản Nhà nước"),
    ("Unknown", "Không xác định"),
    ("Unclassified", "Thường"),
    ("Confidential", "Mật"),
    ("Secret", "Tối mật"),
    ("Top secret", "Tuyệt mật"),
    ("Vietnamese", "Tiếng Việt"),
    ("Regime header", "Tiêu ngữ"),
    ("Superior authority", "Cơ quan cấp trên"),
    ("Issuing authority", "Cơ quan ban hành"),
    ("Document number and symbol", "Số - Ký hiệu"),
    ("Place and date", "Địa điểm, ngày tháng"),
    ("Subject", "Trích yếu"),
    ("Addressee", "Người nhận"),
    ("Recipients", "Nơi nhận"),
    ("Signer's title", "Chức vụ người ký"),
    ("Signer", "Người ký"),
    ("Urgency", "Mức độ khẩn"),
    ("Circulation restrictions", "Chế độ sử dụng"),
    ("Current file", "File hiện tại"),
    ("Elapsed time", "Thời gian"),
    ("Stage", "Giai đoạn"),
    ("Select", "Chọn"),
    ("Reset repository data?", "Reset dữ liệu kho?"),
    (
        "This deletes all data in the internal Repository: - Dossiers and metadata - PDFs added to the Repository - Fast-search indexes Current Repository: {} This action cannot be undone.",
        "Thao tác này sẽ xóa toàn bộ dữ liệu trong Kho lưu trữ nội bộ: - Hồ sơ và metadata - PDF đã chuyển vào kho - Chỉ mục tìm kiếm nhanh Kho hiện tại: {} Không thể hoàn tác.",
    ),
    ("Repository data was deleted and an empty Repository was created.", "Đã xóa dữ liệu kho và tạo lại kho rỗng."),
    ("A Repository import is running. Wait for it to finish and try again.", "Kho đang có tác vụ chuyển dữ liệu. Hãy chờ hoàn tất rồi thử lại."),
    ("The confirmation text is incorrect. Repository data was not deleted.", "Chữ xác nhận không đúng. Dữ liệu kho chưa bị xóa."),
    ("Could not reset repository data: {}", "Không reset được dữ liệu kho: {}"),
    ("Confirm repository reset", "Xác nhận reset dữ liệu kho"),
    ("Type '{}' exactly to confirm deletion of all Repository data:", "Gõ chính xác '{}' để xác nhận xóa toàn bộ dữ liệu kho:"),
    ("Repository data reset: {}", "Đã reset dữ liệu kho: {}"),
    ("Repository data reset failed: {}", "Reset dữ liệu kho thất bại: {}"),
    ("Loading libraries for Scan PDF -> Word: {}. The task will start automatically when loading finishes.", "Đang tải thư viện cho Chuyển scan PDF -> Word: {}. Tác vụ sẽ tự chạy sau khi tải xong."),
    ("ModelManager is not ready; OCR cannot start.", "ModelManager chưa sẵn sàng; chưa thể chạy OCR."),
    ("Could not load {}; Scan PDF -> Word cannot start.", "Không tải được {}; chưa thể chạy Chuyển scan PDF -> Word."),
    ("Starting OCR pool (ScreenAI DLL workers)...", "Khởi động OCR pool (ScreenAI DLL workers)..."),
    ("Loading table_anchored_merger (GMFT + Docling v1 ONNX)...", "Tải table_anchored_merger (GMFT + Docling v1 ONNX)..."),
    ("Using main pipeline: DocLayout bbox + GMFT-ONNX + Docling v1 step-cache ONNX", "Dùng pipeline chính: DocLayout bbox + GMFT-ONNX + Docling v1 step-cache ONNX"),
    ("Loading KIE inference (mode={})...", "Tải KIE inference (mode={})..."),
    ("Loading OCR engine (ScreenAI)...", "Tải OCR engine (ScreenAI)..."),
    ("Loading spelling-correction module (Proton CT2)...", "Tải module sửa chính tả (Proton CT2)..."),
    ("Import ZIP into Repository", "Nhập ZIP vào Kho"),
    ("Translating to Vietnamese...", "Đang dịch tiếng Việt..."),
    ("Translation skipped: {}", "Bỏ qua dịch: {}"),
    ("Loading {}...", "Đang tải {}..."),
    ("Loading library {}...", "Đang tải thư viện {}..."),
    ("Releasing {}...", "Đang giải phóng {}..."),

    # Dossier/session fields
    ("1 year", "1 năm"),
    ("5 years", "5 năm"),
    ("10 years", "10 năm"),
    ("20 years", "20 năm"),
    ("30 years", "30 năm"),
    ("50 years", "50 năm"),
    ("60 years", "60 năm"),
    ("70 years", "70 năm"),
    ("Fonds name", "Tên phông"),
    ("Archive catalog name", "Tên mục lục"),
    ("Retention period", "Thời hạn bảo quản"),
    ("Physical condition", "Tình trạng vật lý"),
    ("Term", "Nhiệm kỳ"),
    ("Sheet count", "Số lượng tờ"),
    ("Page count", "Số lượng trang"),
    ("Topic", "Chuyên đề"),
    ("Dossier notes", "Chú thích"),
    ("Topic (optional)", "Chuyên đề (tùy chọn)"),
    ("Notes (optional)", "Chú thích (tùy chọn)"),
    ("Sheet count (blank = calculate automatically)", "Số tờ (để trống = tự tính)"),
    ("Page count (blank = actual scanned pages)", "Số trang (để trống = theo scan thực tế)"),
    ("The term may contain at most {} characters.", "Nhiệm kỳ tối đa {} ký tự."),
    ("The term cannot exceed {} characters", "Nhiệm kỳ không được vượt quá {} ký tự"),
    ("Fonds name (maximum 1000 characters) — must match the archive system", "Tên phông (tối đa 1000 ký tự) - đảm bảo giống hệ thống kho lưu trữ"),
    ("Archive catalog name (maximum 1000 characters) — must match the archive system", "Tên mục lục (tối đa 1000 ký tự) - đảm bảo giống hệ thống kho lưu trữ"),
    ("(untitled)", "(chưa đặt tên)"),
    ("Dossier", "Hồ sơ"),
    ("Unclassified dossier", "Hồ sơ chưa phân loại"),
    ("(no metadata)", "(không có metadata)"),
    ("(untitled)", "(không tiêu đề)"),
    ("(no content)", "(không có nội dung)"),
    ("<b>📁 Dossier:</b> {}", "<b>📁 Hồ sơ:</b> {}"),
    ("Page count differs from the actual scan", "Số lượng trang khác thực tế"),
    (
        "The page count you entered ({}) differs from the actual scanned page count ({}). Do you want to keep the entered value?",
        "Số lượng trang bạn nhập ({}) khác tổng trang scan thực tế ({}). Bạn có muốn giữ giá trị đã nhập?",
    ),
    ("Differs from the actual scanned page count ({}).", "Khác tổng trang scan thực tế ({})."),

    # Digitization: preprocessing, split, and KIE
    ("Step 2 - KIE extraction", "Bước 2 - Trích xuất KIE"),
    (
        "Step 2 already contains files. Selecting a new folder will cancel the current process — continue?",
        "Bạn đã có danh sách file trong Bước 2. Chọn thư mục mới sẽ huỷ tiến trình hiện tại — tiếp tục?",
    ),
    ("The PDF folder has been selected.", "Đã chọn xong thư mục PDF."),
    (
        "Do you want to process it now or only save the path for later?",
        "Bạn muốn xử lý ngay hay chỉ lưu đường dẫn để xử lý sau?",
    ),
    ("Process", "Xử lý"),
    ("Skip", "Bỏ qua"),
    ("Processing Step 2 files", "Đang preprocess bước 2"),
    ("Preparing preprocessing...", "Đang chuẩn bị preprocess..."),
    ("Preprocessing PDFs before OCR/KIE...", "Đang tiền xử lý PDF trước OCR/KIE..."),
    ("Preprocessing", "Preprocess"),
    ("Preprocessing complete. Starting OCR/KIE...", "Preprocess xong. Đang chuyển sang OCR/KIE..."),
    ("Preprocessing complete; preparing the next file...", "Đã preprocess xong, chuẩn bị file tiếp theo..."),
    ("Unsaved changes", "Có thay đổi chưa lưu"),
    (
        "You changed the current document's information. Save it before moving on?",
        "Bạn đã chỉnh thông tin của văn bản hiện tại. Lưu lại trước khi chuyển?",
    ),
    ("Unable to check changes", "Không thể kiểm tra thay đổi"),
    ("Could not check unsaved KIE changes: {}", "Không kiểm tra được thay đổi KIE chưa lưu: {}"),
    ("Unable to discard changes", "Không thể bỏ thay đổi"),
    ("Could not restore the KIE data from before editing: {}", "Không khôi phục được KIE trước khi sửa: {}"),
    ("Classified document: {}", "Văn bản mật: {}"),
    ("Classified document: {} {} {}", "Văn bản mật: {} {} {}"),
    (
        "The document type could not be identified. Select it before exporting.",
        "Chưa xác định được tên loại văn bản. Hãy chọn lại trước khi xuất.",
    ),
    ("OCRing long PDF", "Đang OCR file dài"),
    ("Preparing OCR...", "Đang chuẩn bị OCR..."),
    ("Cannot render PDF.", "Không thể render PDF."),
    ("OCR/split failed: {}", "OCR/tách file thất bại: {}"),
    ("Split failed: {}", "Tách file thất bại: {}"),
    ("Cannot open PDF: {}", "Không thể mở PDF: {}"),
    ("{} Background OCR: {}/{} pages", "{} OCR ngầm: {}/{} trang"),
    ("✓ OCR complete {}/{} pages", "✓ OCR xong {}/{} trang"),
    ("Drag a PDF here or use the \"Select PDF\" button above", "Kéo thả file PDF vào đây hoặc dùng nút \"Chọn PDF\" ở thanh trên"),
    ("📄  Drag and drop a PDF here, or click to select...", "📄  Kéo thả file PDF vào đây, hoặc bấm để chọn..."),
    ("OCRing pages. You can cancel if the wrong file was selected.", "Đang OCR từng trang. Có thể hủy nếu chọn nhầm file."),
    ("Applying document-split suggestions...", "Đang áp dụng gợi ý tách văn bản..."),
    ("Updating interface", "Đang cập nhật giao diện"),
    ("OCR is complete and document splits were suggested automatically.", "Đã OCR xong và tự động gợi ý tách văn bản."),
    ("Nearest page", "Trang gần nhất"),
    ("Automatic split", "Split tự động"),
    ("OCR complete. Building the OCR PDF and detecting document starts...", "OCR xong. Đang dựng PDF OCR và phát hiện trang đầu..."),
    ("Finishing", "Đang hoàn tất"),
    ("Detecting document starts with LightGBM...", "Đang phát hiện trang đầu bằng LightGBM..."),
    ("Splitting documents", "Đang tách văn bản"),
    ("Detecting document starts with LightGBM: {}/{} pages", "Đang xác định trang đầu bằng LightGBM: {}/{} trang"),

    # Signing configuration and signing screens
    ("No files loaded", "Chưa nạp file"),
    ("No files from Step 2", "Chưa có file từ Bước 2"),
    ("Loaded {} files from Step 2", "Đã nạp {} file từ Bước 2"),
    ("PDFs to sign", "Danh sách PDF cần ký"),
    ("Add files", "Thêm file"),
    ("Add folder", "Thêm thư mục"),
    ("Remove selected", "Xóa chọn"),
    ("Remove all", "Xóa tất cả"),
    ("Waiting to sign", "Chờ ký"),
    ("Signed", "Đã ký"),
    ("Already signed", "Đã ký (có sẵn)"),
    ("File name", "Tên tập tin"),
    ("Page number", "Trang số"),
    ("Signed file", "File đã ký"),
    ("Select PDF files", "Chọn file PDF"),
    ("Select a folder containing PDFs", "Chọn thư mục chứa PDF"),
    ("Signing 0/{} files...", "Đang ký 0/{} file..."),
    ("Signing {}/{}: {}", "Đang ký {}/{}: {}"),
    ("Complete: {} succeeded, {} failed.", "Xong: {} thành công, {} lỗi."),
    ("Digital signing failed: {}", "Ký số thất bại: {}"),
    ("Digital-signing error", "Lỗi ký số"),
    ("OCR complete", "OCR xong"),
    ("OCR failed ({}), signing the original", "OCR thất bại ({}), ký bản gốc"),
    ("OCR engine is not installed: {}", "OCR engine chưa cài đặt: {}"),
    ("Could not open PDF for OCR: {}", "cannot open PDF for OCR: {}"),
    ("PDF/A conversion failed: {}", "PDF/A convert failed: {}"),
    ("Unsupported field: {}", "Trường không hỗ trợ: {}"),
    ("Processing 0/{} files…", "Đang xử lý 0/{} file…"),
    ("{} OCRing page {}/{}: {}", "{} Đang OCR {}/{} trang: {}"),
    ("{} OCR {}/{}", "{} OCR {}/{}"),
    ("Dossier information", "Thông tin hồ sơ"),
    (
        "There is no open digitization session whose dossier information can be edited.",
        "Không có phiên số hóa đang mở để sửa thông tin hồ sơ.",
    ),
    ("Missing library", "Thiếu thư viện"),
    ("Stopping after the current file...", "Đang dừng sau file hiện tại..."),
    ("Stopping after the current file…", "Đang dừng sau file hiện tại…"),
    ("Select a digital certificate.", "Hãy chọn chứng thư số."),
    ("There are no valid PDFs to sign.", "Chưa có file PDF hợp lệ để ký."),
    ("Signature template", "Mẫu chữ ký"),
    ("The display template cannot be empty.", "Mẫu hiển thị không được để trống."),
    ("Stamp image", "Hình dấu"),
    ("Stamp image not found:\n{}", "Không tìm thấy hình dấu:\n{}"),
    ("TSA server", "Máy chủ TSA"),
    (
        "Enter a TSA server address or disable timestamping.",
        "Nhập địa chỉ máy chủ TSA hoặc tắt chức năng cấp dấu thời gian.",
    ),
    ("The TSA address must start with http:// or https://.", "Địa chỉ TSA phải bắt đầu bằng http:// hoặc https://."),
    ("Unsupported field: {{}}", "Trường không hỗ trợ: {{}}"),
    ("Some files could not be signed", "Có lỗi ký số"),
    ("Archive Step 3: keeping signed filename {}: {}", "Archive Step 3: không đổi tên file đã ký {}: {}"),
    ("PDF/A conversion failed: {}. Falling back to signing the original file.", "PDF/A convert failed: {}. Fallback: ký file gốc thay vì PDF/A."),
    ("Input folder:", "Thư mục đầu vào:"),
    ("Output folder:", "Thư mục đầu ra:"),
    ("Choose the folder containing PDFs to sign…", "Chọn thư mục chứa các file PDF cần ký…"),
    ("Only .pdf files in this folder and its subfolders are loaded.", "Chỉ các file .pdf trong thư mục (và thư mục con) được nạp."),
    ("Choose the folder for signed PDFs…", "Chọn thư mục sẽ chứa các file PDF đã ký…"),
    ("Automatically OCR files that do not contain text", "Tự động OCR nếu phát hiện tập tin chưa OCR"),
    (
        "Scanned-image files without a text layer are OCRed before signing so the signature can avoid document text. Digital PDFs with text are read directly without OCR. If disabled, scanned files are signed at the selected X/Y position and text overlap cannot be avoided.",
        "Các file là ảnh scan (chưa có text layer) sẽ được OCR trước khi ký để chữ ký tránh đè lên nội dung văn bản. File PDF điện tử (đã có text) được trích text trực tiếp, không OCR. Nếu tắt, file scan sẽ ký ở đúng vị trí X/Y đã chọn (không tránh được chữ vì không có text layer).",
    ),
    ("Select input folder (containing PDFs)", "Chọn thư mục đầu vào (chứa PDF)"),
    ("Select output folder (signed PDFs)", "Chọn thư mục đầu ra (PDF đã ký)"),
    ("Loaded {} PDF files from the input folder.", "Đã nạp {} file PDF từ thư mục đầu vào."),
    ("Start signing", "Bắt đầu ký số"),
    ("Open signed-files folder", "Mở thư mục đã ký"),
    ("No output folder has been selected.", "Chưa chọn thư mục đầu ra."),
    ("Load list", "Nạp danh sách"),
    ("Choose…", "Chọn…"),
    ("Load PDF list", "Nạp danh sách PDF"),
    ("Select the input folder first.", "Hãy chọn thư mục đầu vào trước."),
    ("Select an input folder.", "Hãy chọn thư mục đầu vào."),
    ("Select an output folder.", "Hãy chọn thư mục đầu ra."),
    ("Same input and output folder", "Thư mục trùng nhau"),
    (
        "The output folder is the same as the input folder. Original files will be overwritten by signed files. Continue?",
        "Thư mục đầu ra trùng thư mục đầu vào. Các file gốc sẽ bị ghi đè bằng file đã ký. Tiếp tục?",
    ),
    ("There are no valid PDFs to sign. Load the list first.", "Chưa có file PDF hợp lệ để ký. Hãy nạp danh sách."),
    ("OCR is not ready", "OCR chưa sẵn sàng"),
    (
        "The OCR engine (ScreenAI) is not installed. Disable 'Automatic OCR' or install the OCR engine in Settings.",
        "Engine OCR (ScreenAI) chưa được cài đặt. Hãy tắt tùy chọn 'Tự động OCR' hoặc cài engine OCR trong phần Cài đặt.",
    ),
    ("Delete stamp image", "Xóa hình dấu"),
    ("Digital certificate", "Chứng thư số"),
    ("Reload certificates", "Tải lại chứng thư"),
    ("Timestamp service", "Dịch vụ cấp dấu thời gian"),
    ("Use TSA timestamping", "Sử dụng TSA cấp dấu thời gian"),
    ("RFC 3161 timestamp server address.", "Địa chỉ máy chủ cấp dấu thời gian RFC 3161."),
    ("Signature content", "Nội dung chữ ký"),
    ("+ Add", "+ Thêm"),
    ("✎ Rename", "✎ Đổi tên"),
    ("🗑 Delete", "🗑 Xóa"),
    ("Select image", "Chọn ảnh"),
    ("Below stamp", "Dưới dấu"),
    ("Right of stamp", "Bên phải dấu"),
    ("Signature position", "Vị trí chữ ký"),
    ("Auto-fit width/height", "Tự khớp rộng/cao"),
    (
        "Keep Page, X, and Y unchanged. Recalculate only Width/Height to fit the selected certificate and template at the standard 8pt font size.",
        "Giữ nguyên Trang, X và Y. Chỉ tính lại Rộng/Cao đủ chứa nội dung mẫu theo chứng thư đang chọn, cỡ chữ chuẩn 8pt.",
    ),
    ("X/Y is the top-left corner. Auto-fit only changes Width/Height.", "X/Y là góc trên trái. Tự khớp chỉ đổi Rộng/Cao."),
    ("Avoid text when placing the signature", "Tự tránh vùng có chữ khi đặt chữ ký"),
    (
        "Before signing, the application reads text/OCR on the page and shrinks the signature box into free space from X/Y while keeping a gap from PDF text. If the page has no text layer or no suitable free region is found, the current position is used.",
        "Trước khi ký, phần mềm đọc text/OCR trên trang rồi thu nhỏ khung chữ ký theo khoảng trống từ vị trí X/Y, có chừa khoảng hở với text PDF. Nếu trang không có text layer hoặc không tìm được vùng trống phù hợp thì dùng vị trí hiện tại.",
    ),
    ("Convert to PDF/A-2b before signing", "Convert PDF/A-2b trước khi ký"),
    ("Select stamp image", "Chọn hình dấu"),
    ("Images (*.png *.jpg *.jpeg *.bmp *.webp *.tif *.tiff)", "Ảnh (*.png *.jpg *.jpeg *.bmp *.webp *.tif *.tiff)"),
    ("New signature template", "Mẫu chữ ký mới"),
    ("Template name:", "Tên mẫu:"),
    ("Rename template", "Đổi tên mẫu"),
    ("New name:", "Tên mới:"),
    ("Delete signature template", "Xóa mẫu chữ ký"),
    ("Unable to connect to TSA", "Không kết nối được TSA"),
    ("Retry TSA", "Thử lại TSA"),
    ("Missing digital-signing library", "Thiếu thư viện ký số"),
    ("TSA server:", "Máy chủ TSA:"),
    ("Template:", "Mẫu:"),
    ("Stamp image:", "Hình dấu:"),
    ("Display content:", "Nội dung hiển thị:"),
    ("Fields:", "Trường:"),
    ("Reinstall pikepdf to use this feature.", "Cài lại pikepdf để dùng tính năng này."),
    (
        "Convert the PDF to PDF/A-2b (ISO 19005-2) before signing. Preserve the original text layer and fonts to avoid mojibake.",
        "Convert PDF sang PDF/A-2b (chuẩn ISO 19005-2) trước khi ký số. Giữ nguyên text layer + font gốc, tránh lỗi mojibake.",
    ),
    ("The image file is invalid.", "File ảnh không hợp lệ."),
    ("This name is reserved for the default template.", "Tên này đang dùng cho mẫu mặc định."),
    ("Template '{}' already exists. Overwrite it?", "Mẫu '{}' đã tồn tại. Ghi đè?"),
    ("The TSA address is invalid.", "Địa chỉ TSA không hợp lệ."),
    ("Checking TSA connection...", "Đang kiểm tra kết nối TSA..."),
    ("Digital signing was cancelled.", "Đã hủy ký số."),
    ("Select a certificate first.", "Hãy chọn chứng thư trước."),
    ("Width:", "Rộng:"),
    ("Could not save the stamp image.", "Không lưu được hình dấu."),
    ("Missing image", "Mất ảnh"),
    ("No certificates with a private key were found", "Không tìm thấy chứng thư có khóa bí mật"),
    ("Certificate error", "Lỗi chứng thư"),
    ("Could not read the Windows certificate store:\n{}", "Không đọc được Windows cert store:\n{}"),

    # OCR accuracy and classified-file scan
    (
        "Measurement workflow: ① Download the sample PDF. ② Process it with another OCR application. ③ Upload that application's result here for comparison.",
        "Quy trình đo: ① Tải file PDF mẫu về máy. ② Dùng phần mềm OCR khác xử lý file đó. ③ Tải PDF kết quả của họ lên đây để so sánh.",
    ),
    ("Comparison results will appear here after upload...", "Kết quả so sánh sẽ hiện ở đây sau khi tải file lên..."),
    ("Process this file with another OCR application, then return to Step 2.", "Đem file này cho phần mềm OCR khác xử lý, rồi quay lại bước 2."),
    ("📥 Download groundtruth.pdf", "📥  Tải groundtruth.pdf về"),
    ("Compare accuracy", "So sánh độ chính xác"),
    ("Save sample file", "Lưu file mẫu"),
    ("Sample file downloaded", "Đã tải file mẫu"),
    ("Select an OCRed PDF", "Chọn PDF đã OCR"),
    ("Sample file missing", "Thiếu file mẫu"),
    ("No file selected", "Chưa có file"),
    ("Drag and drop a PDF or click Step 2 to select one.", "Vui lòng kéo thả hoặc bấm vào Bước 2 để chọn PDF."),
    ("Select folder to scan", "Chọn thư mục cần quét"),
    ("Select folder", "Chọn thư mục"),
    ("Quick scan — first page only", "Tìm nhanh — chỉ trang đầu"),
    ("First page", "Trang đầu"),
    ("Thorough search", "Tìm kỹ"),
    ("Original PDF", "PDF gốc"),
    ("Image converted to PDF", "Ảnh chuyển sang PDF"),
    ("DOC/DOCX converted to PDF", "DOC/DOCX chuyển sang PDF"),
    ("DOC/DOCX converted to PDF page 1", "DOC/DOCX chuyển sang PDF trang 1"),
    ("Existing PDF text", "PDF text sẵn có"),
    ("Direct DOCX text", "DOCX text trực tiếp"),
    ("Direct DOC text", "DOC text trực tiếp"),
    ("Could not read DOC text directly", "DOC không đọc được text trực tiếp"),
    ("first page", "trang đầu"),
    ("first DOC/DOCX page", "DOC/DOCX trang đầu"),
    ("checked all {} pages", "kiểm tất cả {} trang"),
    (
        "On: check only the first page of each document (very fast). Off: thorough scan — scan every page for classified markings, then use LightGBM to filter pages that are not document starts.",
        "Bật: chỉ kiểm tra trang đầu mỗi tài liệu (rất nhanh). Tắt: Tìm kỹ — quét toàn bộ trang, phát hiện dấu mật trên mọi trang rồi chạy LightGBM để lọc các trang không phải trang đầu văn bản.",
    ),
    ("Start scan", "Bắt đầu quét"),
    ("No folder selected", "Chưa có thư mục"),
    ("Select a folder to scan.", "Vui lòng chọn thư mục cần quét."),
    ("Processing...", "Đang xử lý..."),
    ("Step 1 — Download the sample PDF", "Bước 1 — Tải file PDF mẫu về máy"),
    ("Step 2 — Upload the OCRed PDF from another application", "Bước 2 — Tải PDF đã OCR (của phần mềm khác) lên"),
    ("Sample file saved: {}", "Đã lưu file mẫu: {}"),
    ("Sample file not found at: {}", "Không tìm thấy file mẫu tại: {}"),
    ("Could not save file: {}", "Không thể lưu file: {}"),
    (
        "Saved to: {} Process this file with another OCR application, then upload its result in Step 2.",
        "Đã lưu vào: {} Đem file này cho phần mềm OCR khác xử lý, rồi quay lại tải kết quả lên ở Bước 2.",
    ),

    # Repository
    ("Select date", "Chọn ngày"),
    ("Move to Repository?", "Chuyển vào Kho?"),
    ("The dossier ZIP was exported.", "Đã xuất hồ sơ nén."),
    ("Do you want to move this dossier package into the internal Repository?", "Bạn có muốn chuyển bộ hồ sơ này vào Kho lưu trữ nội bộ không?"),
    ("Moving into Repository…", "Đang chuyển vào Kho lưu trữ…"),
    ("Move to Repository", "Chuyển vào Kho"),
    ("No dossier is available to export. Run Step 2 first.", "Chưa có hồ sơ để xuất. Hãy chạy Bước 2 trước."),
    ("No dossier is available to move. Run Step 2 first.", "Chưa có hồ sơ để chuyển. Hãy chạy Bước 2 trước."),
    (
        "The dossier identifier is incomplete. Return to Step 1 and enter the identifier, fonds code, catalog, and dossier code before moving it to the Repository.",
        "Thiếu mã định danh hồ sơ. Hãy quay về Bước 1 nhập đủ mã định danh, mã phông, mục lục, hồ sơ trước khi chuyển vào Kho.",
    ),
    ("There are no valid files to move (PDF or canonical JSON is missing).", "Không có file hợp lệ để chuyển (thiếu PDF hoặc canonical JSON)."),
    ("Move to Repository complete", "Chuyển vào Kho hoàn tất"),
    ("Dossiers: {}", "Hồ sơ: {}"),
    ("Documents imported: {}", "Văn bản đã nhập: {}"),
    ("Duplicates: {}", "Trùng thừa: {}"),
    ("(skipped {}, kept {})", "(bỏ qua {}, giữ lại {})"),
    ("Errors: {}", "Lỗi: {}"),
    ("You can search immediately.", "Có thể tìm kiếm ngay."),
    ("Move to Repository failed: {}", "Chuyển vào Kho thất bại: {}"),
    ("Import directly into the Repository without rerunning OCR/KIE? Select “No” to open Step 2 and edit the information.", "Nhập thẳng vào Kho lưu trữ (không chạy lại OCR/KIE)? Chọn “No” nếu muốn mở vào Bước 2 để chỉnh sửa thông tin."),
    ("Import into Repository", "Nhập vào Kho lưu trữ"),
    ("There are no valid documents to import (PDF or accompanying OCR/KIE data is missing).", "Không có văn bản hợp lệ để nhập (thiếu PDF hoặc dữ liệu OCR/KIE kèm theo)."),
    ("There are no valid PDFs to export.", "Không có PDF hợp lệ để xuất."),
    ("Export failed: {}", "Xuất thất bại: {}"),
    ("Delete temporary files?", "Xóa file tạm?"),
    ("The dossier is safely stored in the Repository. Delete this dossier's temporary folder?", "Hồ sơ đã được chuyển vào Kho an toàn. Bạn có muốn xóa thư mục tạm của hồ sơ này không?"),
    ("Edit dossier information", "Sửa thông tin hồ sơ"),
    ("Drag to reorder documents", "Giữ chuột rồi kéo để sắp xếp thứ tự văn bản"),
    ("Select a dossier or document to view details", "Chọn 1 hồ sơ hoặc văn bản để xem chi tiết"),
    ("Containing folder", "Thư mục chứa"),
    ("Edit metadata", "Sửa metadata"),
    ("Related passages", "Đoạn liên quan"),
    ("Related passages ({})", "Đoạn liên quan ({})"),
    ("Metadata matching the filters", "Metadata khớp điều kiện"),
    ("Metadata containing the exact search terms", "Metadata chứa chính xác từ tìm"),
    ("Metadata containing similar terms", "Metadata chứa từ gần giống"),
    ("Document content containing the exact search terms", "Nội dung văn bản chứa chính xác từ tìm"),
    ("Document content containing similar terms", "Nội dung văn bản chứa từ gần giống"),
    ("{} similar metadata items", "{} thông tin gần giống"),
    ("{} similar passages", "{} đoạn gần giống"),
    ("{} matching metadata items", "{} thông tin khớp"),
    ("{} matching passages", "{} đoạn khớp"),
    ("{} approximate matches", "{} lần gần giống"),
    ("{} occurrences", "{} lần xuất hiện"),
    ("Document summary", "Tóm tắt văn bản"),
    ("similar", "gần giống"),
    ("{} matches", "{} lần"),
    ("(no page to display)", "(chưa có trang để hiện)"),
    ("(PDF file does not exist)", "(file PDF không tồn tại)"),
    ("(could not render PDF: {})", "(không render được PDF: {})"),
    ("💾 Save", "💾 Lưu"),
    ("← Dossiers", "← Hồ sơ"),
    ("Loading dossiers…", "Đang tải hồ sơ…"),
    ("Filter by fonds code", "Lọc theo mã phông"),
    ("Filter by catalog number", "Lọc theo số mục lục"),
    ("+ Add document", "+ Thêm văn bản"),
    ("Export dossier ZIP", "Xuất hồ sơ nén"),
    ("Clear selection", "Bỏ chọn"),
    ("Delete selected items", "Xóa mục đã chọn"),
    (
        "Enter natural-language keywords (document number, signer, subject, content...)",
        "Nhập từ khóa tự nhiên (số văn bản, tên người ký, trích yếu, nội dung...)",
    ),
    ("Advanced search", "Tìm kiếm nâng cao"),
    (
        "Filter document information (combined with AND)",
        "Lọc thông tin văn bản (kết hợp AND)",
    ),
    ("← Results", "← Kết quả"),
    ("Search results", "Kết quả tìm kiếm"),
    ("Search results ({})", "Kết quả tìm kiếm ({})"),
    ("Sort the current list", "Sắp xếp danh sách hiện tại"),
    ("Sort:", "Sắp xếp:"),
    ("Clear search", "Xóa tìm kiếm"),
    ("All", "Tất cả"),
    ("OCR content", "Nội dung OCR"),
    ("Document information", "Thông tin văn bản"),
    ("Search scope", "Phạm vi tìm kiếm"),
    ("Fonds → Catalog → Dossier", "Phông → Mục lục → Hồ sơ"),
    ("Recently stored", "Mới lưu gần đây"),
    ("Dossier name A–Z", "Tên hồ sơ A–Z"),
    ("Document ordinal", "Số thứ tự văn bản"),
    ("Newest issue date", "Ngày ban hành mới nhất"),
    ("Document name A–Z", "Tên văn bản A–Z"),
    ("Best match", "Phù hợp nhất"),
    ("Matches filters", "Khớp bộ lọc"),
    (
        "Matches keywords (including without diacritics)",
        "Khớp từ khóa (kể cả không dấu)",
    ),
    ("Approximate results", "Kết quả gần đúng"),
    ("Open dossier", "Mở hồ sơ"),
    ("{}Results ({})", "{}Kết quả ({})"),
    ("All {}", "Tất cả {}"),
    (
        "Search document numbers, signers, authorities, subjects...",
        "Tìm số ký hiệu, người ký, cơ quan, trích yếu...",
    ),
    ("Search OCR content...", "Tìm trong nội dung OCR..."),
    (
        "Search document information and OCR content...",
        "Tìm trong thông tin văn bản và nội dung OCR...",
    ),
    (
        "Search OCR content; open ▾ to add document-information filters",
        "Tìm trong nội dung OCR; mở ▾ để lọc thêm thông tin văn bản",
    ),
    (
        "The conditions below are combined with the content query using AND.",
        "Các điều kiện dưới đây được kết hợp AND với nội dung cần tìm.",
    ),
    ("Searching OCR content...", "Đang tìm trong nội dung OCR..."),
    (
        "Searching content and filtering document information...",
        "Đang tìm nội dung và lọc thông tin văn bản...",
    ),
    (
        "Filtering document information...",
        "Đang lọc thông tin văn bản...",
    ),
    ("{} results · viewing {}/{}", "{} kết quả · đang xem {}/{}"),
    ("<b>Fonds code:</b> {}", "<b>Mã phông:</b> {}"),
    ("<b>Fonds name:</b> {}", "<b>Tên phông:</b> {}"),
    ("<b>Catalog number:</b> {}", "<b>Số mục lục:</b> {}"),
    ("<b>Catalog name:</b> {}", "<b>Tên mục lục:</b> {}"),
    ("<b>Dossier number:</b> {}", "<b>Số hồ sơ:</b> {}"),
    ("<b>Dossier name:</b> {}", "<b>Tên hồ sơ:</b> {}"),
    ("Searching all document data...", "Đang tìm trong toàn bộ văn bản..."),
    (
        "Searching document information...",
        "Đang tìm trong thông tin văn bản...",
    ),
    (
        "The dossier for this document could not be found.",
        "Không tìm thấy hồ sơ của văn bản.",
    ),
    (
        "No suitable documents were found. Shorten the keywords or remove some filters.",
        "Không có văn bản phù hợp. Hãy rút gọn từ khóa hoặc bớt điều kiện lọc.",
    ),
    ("<b>Time:</b> {}", "<b>Thời điểm:</b> {}"),
    ("In Content", "Trong Nội dung"),
    ("In Metadata", "Trong Metadata"),
    ("Import from ZIP", "Nhập từ ZIP"),
    (
        "Import one or more exported dossier ZIP files (with .json.zst) into the Repository without rerunning OCR/KIE. ZIP files can also be dragged directly onto this screen.",
        "Nhập một hoặc nhiều file ZIP hồ sơ đã xuất (kèm .json.zst) vào Kho — không chạy lại OCR/KIE. Có thể kéo thả trực tiếp các file ZIP vào màn hình này.",
    ),
    ("⚙ Repository location", "⚙ Vị trí kho"),
    ("Select repository location", "Chọn vị trí kho lưu trữ"),
    ("Select a dossier in the left column to view its documents.", "Chọn một hồ sơ ở cột trái để xem các văn bản bên trong."),
    ("{} dossiers", "{} hồ sơ"),
    ("Searching…", "Đang tìm…"),
    ("{} matching documents", "{} văn bản khớp"),
    ("Error: {}", "Lỗi: {}"),
    ("Select a folder for the ZIP file", "Chọn thư mục để lưu file ZIP"),
    ("Exporting dossier ZIP…", "Đang xuất hồ sơ nén…"),
    ("Select dossier ZIP files to import", "Chọn các file ZIP hồ sơ để nhập vào Kho"),
    ("Import into Repository?", "Nhập vào Kho lưu trữ?"),
    ("Importing ZIP files into Repository…", "Đang nhập ZIP vào Kho lưu trữ…"),
    ("Delete dossier?", "Xóa hồ sơ?"),
    ("Delete dossier '{}' and all {} documents in it? This action cannot be undone.", "Xóa hồ sơ '{}' và toàn bộ {} văn bản trong đó? Không thể hoàn tác."),
    ("Delete {} selected dossiers and all documents in them? This action cannot be undone.", "Xóa {} hồ sơ đã chọn và toàn bộ văn bản bên trong? Không thể hoàn tác."),
    ("Delete document?", "Xóa văn bản?"),
    ("Delete {} selected documents? This action cannot be undone.", "Xóa {} văn bản đã chọn? Không thể hoàn tác."),
    ("Review KIE ({}/{})", "Kiểm tra KIE ({}/{})"),
    ("Review KIE {}/{}: {}", "Kiểm tra KIE {}/{}: {}"),
    (
        "Correct the bounding boxes if needed, then click Save and continue to add the document to the Repository.",
        "Sửa bbox nếu cần, bấm Lưu và tiếp tục để đưa văn bản vào Kho.",
    ),
    ("Save and continue", "Lưu và tiếp tục"),
    ("Select PDF files to add", "Chọn file PDF cần thêm"),
    ("Preparing 0/{}", "Chuẩn bị 0/{}"),
    ("Add documents", "Thêm văn bản"),
    ("All catalogs", "Tất cả mục lục"),
    ("Could not open the repository", "Chưa mở được kho"),
    ("Enter information in the fields below", "Vui lòng nhập thông tin vào các trường bên dưới"),
    ("Searching document content...", "Đang tìm trong nội dung..."),
    ("Searching metadata...", "Đang tìm trong metadata..."),
    ("No valid dossiers are available to export.", "Chưa có hồ sơ hợp lệ để xuất."),
    ("Exporting {}/{}: {}", "Đang xuất {}/{}: {}"),
    ("No dossiers could be exported.", "Không xuất được hồ sơ nào."),
    ("Exported {} ZIP files containing {} PDFs.", "Đã xuất {} file ZIP với {} PDF."),
    ("Folder: {}", "Thư mục: {}"),
    ("{} dossiers failed; see the activity log for details.", "Có {} hồ sơ lỗi, xem nhật ký để biết chi tiết."),
    ("Another ZIP import is running. Wait for it to finish.", "Một lệnh nhập ZIP khác đang chạy. Vui lòng đợi hoàn tất."),
    ("No dossiers could be imported:", "Không nhập được hồ sơ nào:"),
    ("ZIP import complete", "Nhập từ ZIP hoàn tất"),
    ("ZIP import failed: {}", "Nhập ZIP thất bại: {}"),
    ("Rename dossier code?", "Đổi mã hồ sơ?"),
    (
        "This renames all PDFs and accompanying OCR data and moves the storage folder. {} → {} Documents to rename: {} Continue?",
        "Thao tác này sẽ đổi tên toàn bộ PDF, dữ liệu OCR đi kèm và chuyển thư mục lưu trữ. {} → {} Số văn bản sẽ đổi tên: {} Tiếp tục?",
    ),
    ("Reordering will reset numbering", "Kéo thả sẽ đánh lại số thứ tự"),
    (
        "The current document numbering is not a complete sequence (a position was skipped). Reordering will renumber all documents sequentially (1, 2, 3…). Verify each document's order before confirming.",
        "Số thứ tự hiện tại của các văn bản chưa đủ liên tiếp (đã bỏ một vị trí). Việc kéo thả sẽ đánh lại số thứ tự tuần tự (1, 2, 3…). Vui lòng kiểm tra chính xác thứ tự của từng văn bản trước khi xác nhận.",
    ),
    ("Adding to Repository 0/{}", "Đang thêm vào Kho 0/{}"),
    ("OCR/KIE failed", "OCR/KIE thất bại"),
    ("Repository could not be opened: {}", "Không mở được kho: {}"),
    ("All fonds", "Tất cả phông"),
    ("No dossiers match the filters.", "Không có hồ sơ theo bộ lọc."),
    ("The Repository is empty. Use Step 3 in 'Archival digitization' to add a dossier.", "Kho rỗng. Dùng Bước 3 trong 'Số hóa lưu trữ' để chuyển hồ sơ vào."),
    ("Enter metadata keywords or open advanced filters.", "Nhập từ khóa metadata hoặc mở lọc nâng cao."),
    (
        "Search for document numbers, dates, signers, authorities, and subjects in the search box, or click ▾ for specific filters.",
        "Có thể tìm số ký hiệu, ngày tháng, người ký, cơ quan, trích yếu trong ô tìm kiếm; hoặc bấm ▾ để lọc cụ thể.",
    ),
    ("No documents matched the metadata.", "Không tìm thấy văn bản khớp metadata."),
    ("No matching documents were found.", "Không tìm thấy văn bản phù hợp."),
    ("Select one or more dossiers, or click Select all.", "Hãy tick chọn một hoặc nhiều hồ sơ, hoặc bấm Chọn tất cả."),
    ("Repository is busy", "Kho đang bận"),
    ("The Repository is updating its index. Try again in a few seconds.", "Kho đang ghi chỉ mục nền. Vui lòng thử lại sau vài giây."),
    ("Reorder documents", "Sắp xếp văn bản"),
    (
        "Select document-ordinal sorting to drag and drop documents",
        "Chọn sắp xếp theo số thứ tự để kéo thả văn bản",
    ),
    ("Could not update dossier: {}", "Không cập nhật được hồ sơ: {}"),
    ("Deletion failed: {}", "Xóa thất bại: {}"),
    ("Could not reorder documents: {}", "Không sắp xếp lại được văn bản: {}"),
    ("Delete {} dossiers", "Xóa {} hồ sơ"),
    ("Delete {} documents", "Xóa {} văn bản"),
    ("Could not update metadata: {}", "Không cập nhật được metadata: {}"),
    ("date {}", "ngày {}"),
    ("{} documents", "{} tài liệu"),
    ("Stored: {}", "Lưu kho: {}"),
    ("Document to reorder was not found", "Không tìm thấy văn bản cần sắp xếp"),
    ("Document number", "Số ký hiệu"),
    ("Authority", "Cơ quan"),
    ("Fonds", "Phông"),
    ("From date", "Ngày từ"),
    ("To", "Đến"),
    ("Could not create a unique export filename: {}", "Không tạo được tên file xuất không trùng: {}"),
    ("Search failed: {}", "Search lỗi: {}"),
    ("Deleted dossier: {} documents, {} passages, ~{} KB", "Xóa hồ sơ: {} văn bản, {} đoạn, ~{} KB"),
    ("Reordered {} documents and renamed {} PDFs by ordinal number.", "Đã sắp xếp lại {} văn bản; đổi tên {} PDF theo số thứ tự."),
    ("Deleted {} dossiers: {} documents, {} passages, ~{} KB", "Xóa {} hồ sơ: {} văn bản, {} đoạn, ~{} KB"),
    ("Deleted {} documents, {} passages, ~{} KB", "Xóa {} văn bản, {} đoạn, ~{} KB"),
    ("Edit document metadata", "Sửa metadata tài liệu"),
    ("Edit metadata stored in the Repository. Saving also updates the metadata search index.", "Chỉnh metadata đang lưu trong Kho. Sau khi bấm Lưu, chỉ mục tìm kiếm metadata sẽ được cập nhật lại."),
    ("Document metadata updated.", "Đã cập nhật metadata tài liệu."),
    ("Preparing", "Chuẩn bị"),
    ("<b>Fonds / Catalog / Dossier:</b> {} / {} / {}", "<b>Phông / Mục lục / Hồ sơ:</b> {} / {} / {}"),
    ("<b>Documents:</b> {}", "<b>Số văn bản:</b> {}"),
    ("<b>Total pages:</b> {}", "<b>Tổng số trang:</b> {}"),
    ("<b>Stored on:</b> {}", "<b>Ngày lưu kho:</b> {}"),
    ("<b>Dossier:</b> {}", "<b>Hồ sơ:</b> {}"),
    ("<b>Subject:</b> {}", "<b>Trích yếu:</b> {}"),
    ("<b>Information:</b> {}", "<b>Thông tin:</b> {}"),
    ("<b>Document type:</b> {}", "<b>Loại văn bản:</b> {}"),
    ("<b>Confidentiality:</b> <span style='color:{}'>{}</span>", "<b>Độ mật:</b> <span style='color:{}'>{}</span>"),
    ("<b>File:</b> <span style='color:{}; font-weight:600'>{}</span>", "<b>Tệp:</b> <span style='color:{}; font-weight:600'>{}</span>"),
    ("<b>Time:</b> {}", "<b>Thời gian:</b> {}"),
    ("(not selected)", "(chưa chọn)"),
    ("Dossier {} has no valid PDFs to export", "Hồ sơ {} không có PDF hợp lệ để xuất"),
    ("Repository: exported {} dossier ZIPs, {} PDFs → {}", "Kho: đã xuất {} hồ sơ nén, {} PDF → {}"),
    ("Repository: some dossiers failed to export:", "Kho: một số hồ sơ xuất lỗi:"),
    ("Repository: skipped ZIP imports —", "Kho: ZIP bỏ qua khi nhập —"),
    ("• {}-{}-{}-{} — {} documents ({})", "• {}-{}-{}-{} — {} văn bản ({})"),
    ("Repository: ZIP import — {}/{} from {} dossier ZIPs", "Kho: đã nhập ZIP — {}/{} từ {} hồ sơ ZIP"),
    ("Import {} documents from {} dossier ZIPs into the Repository?", "Nhập {} văn bản từ {} hồ sơ ZIP vào Kho lưu trữ?"),
    ("({} documents without .json.zst will be skipped)", "({} văn bản thiếu .json.zst sẽ bỏ qua)"),
    ("{} ZIP files were skipped; see the activity log.", "{} file ZIP bị bỏ qua, xem nhật ký."),
    ("Dossier code changed {} → {}; renamed {} PDFs and accompanying OCR data.", "Đã đổi mã hồ sơ {} → {}; đổi tên {} PDF và dữ liệu OCR đi kèm."),
    ("Dossier information updated.", "Đã cập nhật thông tin hồ sơ."),
    ("Editing/selecting pages", "Đang sửa/chọn trang"),
    ("No PDF selected", "Chưa chọn file PDF"),
    ("OCR/KIE was cancelled", "Đã hủy OCR/KIE"),
    ("OCR/KIE returned no result", "OCR/KIE không trả về kết quả"),
    ("Repository index migration/rebuild is required, but no data was deleted: {}", "Kho cần migration/rebuild chỉ mục nhưng dữ liệu không bị xóa: {}"),
    ("Could not save settings.ini: {}", "Không lưu được settings.ini: {}"),
    ("Could not open file: {}", "Mở file thất bại: {}"),
    ("Could not open folder: {}", "Mở thư mục thất bại: {}"),
    ("{}: identifier/fonds code is missing from the ZIP filename", "{}: thiếu mã định danh / mã phông trong tên ZIP"),
    ("{}: no accompanying OCR/KIE data (.json.zst)", "{}: không có dữ liệu OCR/KIE (.json.zst) kèm theo"),
    ("The Repository is OCR/KIE-processing a new document. Wait for it to finish.", "Kho đang OCR/KIE văn bản mới. Hãy chờ tác vụ hoàn tất rồi thử lại."),
    ("The Repository is adding a document. Wait for it to finish.", "Kho đang thêm văn bản. Hãy chờ tác vụ hoàn tất rồi thử lại."),
    ("Running KIE", "Đang KIE"),
    ("{}: OCR PDF or KIE JSON is missing after processing", "{}: Thiếu PDF OCR hoặc JSON KIE sau khi xử lý"),
    ("Resolution", "Nghị quyết"),
    ("Decision", "Quyết định"),
    ("Directive", "Chỉ thị"),
    ("Conclusion", "Kết luận"),
    ("Regulation", "Quy chế"),
    ("Rules", "Quy định"),
    ("Press release", "Thông cáo"),
    ("Notice", "Thông báo"),
    ("Guidance", "Hướng dẫn"),
    ("Program", "Chương trình"),
    ("Plan", "Kế hoạch"),
    ("Implementation plan", "Phương án"),
    ("Scheme", "Đề án"),
    ("Project", "Dự án"),
    ("Report", "Báo cáo"),
    ("Minutes", "Biên bản"),
    ("Submission", "Tờ trình"),
    ("Contract", "Hợp đồng"),
    ("Official telegram", "Công điện"),
    ("Memorandum", "Bản ghi nhớ"),
    ("Agreement", "Bản thỏa thuận"),
    ("Power of attorney", "Giấy ủy quyền"),
    ("Invitation", "Giấy mời"),
    ("Letter of introduction", "Giấy giới thiệu"),
    ("Leave request", "Giấy nghỉ phép"),
    ("Dispatch slip", "Phiếu gửi"),
    ("Transfer slip", "Phiếu chuyển"),
    ("Notification slip", "Phiếu báo"),
    ("Certified true copy", "Bản sao y"),
    ("Extract copy", "Bản trích sao"),
    ("Duplicate copy", "Bản sao lục"),
    ("Official dispatch", "Công văn"),
    ("Other", "Khác"),
    ("{}: invalid dossier ZIP — {}", "{}: ZIP hồ sơ không hợp lệ — {}"),
    ("{}: could not read — {}", "{}: không đọc được — {}"),
    ("Repository: failed to read OCR JSON for chunking: {}", "Kho: đọc OCR JSON để tạo chunk thất bại: {}"),
    ("Processing error", "Lỗi xử lý"),
    ("Could not open KIE Viewer", "Mở KIE Viewer thất bại"),
    ("OCR/KIE did not return valid files.", "OCR/KIE không trả về file hợp lệ."),
    ("OCR/KIE completed but the temporary OCR PDF was not found: {}", "OCR/KIE đã chạy nhưng không tìm thấy PDF OCR tạm: {}"),
    ("OCR/KIE completed but the temporary KIE JSON was not found: {}", "OCR/KIE đã chạy nhưng không tìm thấy JSON KIE tạm: {}"),
    ("OCR/KIE processed and added {} documents to the dossier.", "Đã OCR/KIE và thêm {} văn bản vào hồ sơ."),
    ("Adding documents failed", "Thêm văn bản thất bại"),
    ("Saving KIE failed", "Lưu KIE thất bại"),
    ("Missing information", "Thiếu thông tin"),
    ("A subject is required before saving.", "Phải nhập Trích yếu trước khi lưu."),
    ("Reading KIE failed", "Đọc KIE thất bại"),
    ("Could not read KIE data after editing: {}", "Không đọc được dữ liệu KIE sau khi sửa: {}"),

    # Classified-file scanner worker/status text
    ("OCR engine is not installed. Disable 'Automatic OCR' or install ScreenAI.", "OCR engine chưa cài đặt. Tắt tùy chọn 'Tự động OCR' hoặc cài engine ScreenAI."),
    ("Could not convert DOC/DOCX to PDF. Microsoft Word or LibreOffice is required.", "Không chuyển được DOC/DOCX sang PDF. Cần Microsoft Word hoặc LibreOffice."),
    ("Unsupported format: {}", "Không hỗ trợ định dạng: {}"),
    ("PDF has no pages to OCR", "PDF không có trang để OCR"),
    ("All {} pages are digital — OCR skipped", "Tất cả {} trang là digital — bỏ OCR"),
    ("Digital DOC/DOCX: using text directly ({} lines, {} characters)", "DOC/DOCX digital: dùng text trực tiếp ({} dòng, {} ký tự)"),
    ("PDF has no pages", "PDF không có trang"),
    ("OCR produced no text; trying rotation/deskew preprocessing...", "OCR không ra chữ, thử preprocess xoay/nghiêng..."),
    ("{}; first page", "{}; trang đầu"),
    ("Initializing OCR...", "Đang khởi tạo OCR..."),
    ("Stopping...", "Đang dừng..."),
    ("Classified-file scan: found {} supported files", "Quét file mật: tìm thấy {} file hỗ trợ"),
    ("{}: scanned {}/{} files, detected {} classified lines, {} errors", "{}: quét {}/{} file, phát hiện {} dòng mật, lỗi {}"),
    ("Classified-file scan: {} - {}/{} files, {} classified lines, {} errors.", "Quét file mật: {} - {}/{} file, {} dòng mật, lỗi {}."),
    ("Preprocessing skipped: {}", "Preprocess bỏ qua: {}"),
    ("Starting single ScreenAI OCR worker (without pool)...", "Khởi động ScreenAI OCR đơn (không dùng pool)..."),
    ("OCR failed on page {}", "OCR thất bại ở trang {}"),
    ("LightGBM failed; could not confirm document-start page: {}", "LightGBM lỗi, không xác nhận trang đầu văn bản: {}"),
    ("Ignored {} marking on page {}: LightGBM did not identify a document-start page", "Bỏ qua dấu {} ở trang {}: LightGBM không xác định là trang đầu văn bản"),
    ("Could not read DOC/DOCX — Word or LibreOffice is required", "Không đọc được DOC/DOCX — cần Word hoặc LibreOffice"),
    ("OCR initialization failed: {}", "Khởi tạo OCR thất bại: {}"),
    ("Scanning {}/{}: {}", "Đang quét {}/{}: {}"),
    ("Could not extract PDF page", "Không trích xuất được trang PDF"),
    ("Page {} classification failed: {} → OCR", "Phân loại trang {} lỗi: {} → OCR"),
    ("OCR pool failed; switching to a single worker: {}", "Pool OCR lỗi, chuyển single-worker: {}"),
    ("[{}] Error: {}", "[{}] Lỗi: {}"),

    # Embedded KIE editor and PDF viewers
    ("⬚ Select & Draw box", "⬚ Chọn & Khoanh vùng"),
    ("Select a metadata field to edit its bounding box", "Chọn field bên metadata để sửa bbox"),
    ("File '{}' has unsaved changes. Save them?", "File '{}' có thay đổi chưa lưu. Bạn muốn lưu không?"),
    ("+ New field on page {}", "+ Trường mới trên trang {}"),
    ("Set as the field being edited", "Đặt làm field đang sửa"),
    ("Delete this field", "Xóa field này"),
    ("Confirm deletion", "Xác nhận xóa"),
    ("Delete field '{}'?\nContent: {}", "Xóa field '{}'?\nNội dung: {}"),
    ("Save error", "Lỗi lưu"),
    ("Could not write file:\n{}", "Không thể ghi file:\n{}"),
    ("Validator error", "Validator lỗi"),
    ("Validator crashed: {}\n\nNot saved.", "Validator crash: {}\n\nKhông lưu."),
    ("Validation errors — cannot save", "Có lỗi — không thể lưu"),
    ("Post-save load error", "Post-save load lỗi"),
    ("Editing:", "Đang sửa:"),
    ("ERROR:", "LỖI:"),
    ("WARNING:", "CẢNH BÁO:"),
    ("… and {} other errors", "… và {} lỗi khác"),
    ("… and {} other warnings", "… và {} cảnh báo khác"),
    ("Select text", "Chọn chữ"),
    ("Enable drag selection; press Ctrl+C to copy", "Bật chế độ kéo chọn chữ; Ctrl+C để copy"),
    ("Previous file", "File trước"),
    ("Next file", "File sau"),
    ("Fit", "Vừa trang"),
    ("Are you sure you want to delete template <b>“{}”</b>?<br>This action cannot be undone.", "Bạn có chắc muốn xóa mẫu <b>“{}”</b>?<br>Hành động này không thể hoàn tác."),
    (
        "Could not connect to the timestamp authority (TSA). You may continue signing with the computer's local time. This is not a trusted TSA timestamp and depends on the computer's date and time settings. Current computer time: {} Adjust the time if necessary, then select Accept to sign with local time.",
        "Không kết nối được máy chủ cấp dấu thời gian (TSA). Bạn có thể tiếp tục ký sử dụng thời gian của máy tính nội bộ. Thời gian này không phải là dấu thời gian tin cậy từ TSA và phụ thuộc vào thiết lập ngày giờ trên máy tính. Thời gian máy hiện tại: {} Vui lòng điều chỉnh thời gian chính xác, sau đó chọn Đồng ý để ký sử dụng thời gian nội bộ.",
    ),
    ("CN: {} OU: {} ORG: {}", "CN: {} OU: {} ORG: {}"),

    # Standalone KIE Viewer
    ("KIE Viewer", "Trình xem KIE"),
    ("Path configuration", "Cấu hình đường dẫn"),
    (
        "Edit the default KIE Viewer paths. Changes are saved to kie_viewer_config.json.",
        "Sửa 4 đường dẫn mặc định của KIE Viewer. Thay đổi sẽ được lưu vào kie_viewer_config.json.",
    ),
    ("Configuration file: {}", "File cấu hình: {}"),
    ("BATCH", "LÔ"),
    ("-- Select batch --", "-- Chọn batch --"),
    ("Refresh (F5)", "Làm mới (F5)"),
    ("Edit", "Sửa"),
    ("+ Field", "+ Field"),
    ("Add a new KIE field", "Thêm một field KIE mới"),
    ("+ Relation", "+ Relation"),
    ("Create a signed_by relation (SIGNER_ROLE → SIGNER_NAME)", "Tạo relation signed_by (SIGNER_ROLE → SIGNER_NAME)"),
    ("Delete field", "Xoá field"),
    ("Delete the selected KIE field", "Xoá field KIE đang được chọn"),
    ("Line mode", "Chế độ dòng"),
    ("On: click one word to select its OCR line. Off: click one word to select only that word.", "Bật: click 1 từ → chọn cả dòng OCR. Tắt: click 1 từ → chọn 1 từ."),
    ("⟲ Rotate", "⟲ Xoay"),
    ("Rotate the PDF another 90° when the displayed text is inverted relative to the OCR boxes.", "Xoay PDF thêm 90° (dùng khi chữ hiển thị bị ngược so với bbox OCR)."),
    ("Copy checked", "Sao chép mục đã chọn"),
    ("Delete checked", "Xoá đã chọn"),
    (
        "Permanently delete checked files from disk (input JSON, output JSON, canonical JSON, and _ocr.pdf). This action cannot be undone.",
        "Xoá HẲN các file đã check khỏi disk (input JSON, output JSON, canonical JSON, _ocr.pdf). Không thể khôi phục.",
    ),
    ("View signer", "Xem người ký"),
    ("Select a batch to begin", "Chọn batch để bắt đầu"),
    ("Label / Text", "Nhãn / Văn bản"),
    ("← → change file | F5 refresh | Esc clear selection | Ctrl+Z/Y undo/redo", "← → chuyển file | F5 làm mới | Esc bỏ chọn | Ctrl+Z/Y hoàn tác"),
    ("Permanently delete selected files", "Xoá HẲN các file đã chọn"),
    (
        "This will PERMANENTLY delete {} files belonging to {} stems: {} For each stem: input JSON, output JSON, canonical JSON, and _ocr.pdf. THIS CANNOT BE UNDONE. Continue?",
        "Sẽ xoá VĨNH VIỄN {} file thuộc {} stem: {} Xoá mỗi stem: input JSON, output JSON, canonical JSON, _ocr.pdf. KHÔNG THỂ KHÔI PHỤC. Tiếp tục?",
    ),
    ("Render 0 / {}", "Render 0 / {}"),
    ("Render {} / {}", "Render {} / {}"),
    ("Copied {} files to the clipboard", "Đã copy {} file vào clipboard"),
    ("Rotated PDF to {}° (temporary; not saved to file)", "Đã xoay PDF → {}° (ghi tạm, không lưu vào file)"),
    ("Creating field {} — drag a region on the PDF to assign its bounding box", "Tạo field {} — kéo vùng trên PDF để gán bbox"),
    ("Created signed_by relation: {} → {}", "Đã tạo relation signed_by: {} → {}"),
    ("Delete relation", "Xoá relation"),
    ("Delete relation {}?", "Xoá relation {}?"),
    ("Deleted relation {}", "Đã xoá relation {}"),
    ("Delete field {}? \"{}\"", "Xoá field {}? \"{}\""),
    ("Deleted field {}", "Đã xoá field {}"),
    (
        "Editing: {} ({} words) Click: toggle • Ctrl+click: add • Shift+click: remove Drag: replace region • Ctrl+drag: add region • Shift+drag: remove region • Esc: exit",
        "Đang sửa: {} ({} word) Click: chọn/bỏ • Ctrl+click: thêm • Shift+click: bỏ Kéo: thay vùng • Ctrl+kéo: thêm vùng • Shift+kéo: bỏ vùng • Esc: thoát",
    ),
    ("Label", "Nhãn"),
    ("No output batch found", "Không tìm thấy batch output"),
    ("Files not found", "Không tìm thấy file"),
    ("No files exist on disk for the selected stems.", "Không có file nào trên disk cho các stem đã chọn."),
    ("Some files could not be deleted", "Một số file không xoá được"),
    ("Deleted {} files. {} files failed: {}", "Đã xoá {} file. {} file lỗi: {}"),
    ("PDF not found", "Không tìm thấy PDF"),
    ("No field selected — click a field on the right to begin editing", "Chưa chọn field — bấm 1 field bên phải để bắt đầu sửa"),
    ("Different page", "Khác trang"),
    ("Field '{}' is on page {}. A bounding box from page {} cannot be added. Delete all existing boxes first or create a new field.", "Field '{}' hiện ở trang {}. Không thể thêm bbox từ trang {}. Hãy xoá hết bbox cũ trước, hoặc tạo field mới."),
    ("Select a file first.", "Hãy chọn một file trước."),
    ("Missing field", "Thiếu field"),
    ("At least one {} field and one {} field are required to create a signed_by relation.", "Cần ít nhất 1 field {} và 1 field {} để tạo relation signed_by."),
    ("EDIT MODE — select a field on the right to begin, or click '+ Field' to create one", "CHẾ ĐỘ SỬA — chọn 1 field bên phải để bắt đầu, hoặc bấm '+ Field' để tạo mới"),
    ("There is no data to save.", "Không có dữ liệu để lưu."),
    ("Output file for '{}' was not found.", "Không tìm thấy file output cho '{}'."),
    ("Canonical OCR missing", "Thiếu canonical OCR"),
    ("No canonical JSON is available for validation. Saving will continue without validation.", "Không có canonical JSON để validate. Save vẫn tiếp tục nhưng KHÔNG được validate."),
    ("Configuration paths cannot be empty.", "Không được để trống đường dẫn cấu hình."),
    ("Could not save configuration: {}", "Không thể lưu cấu hình: {}"),
    ("No PDF", "Không có PDF"),
    ("Page {}", "Trang {}"),
    ("Already exists", "Đã có"),
    ("This relation already exists.", "Relation này đã tồn tại."),
    ("Could not save: {}", "Không thể lưu: {}"),
    ("Validator unavailable", "Validator không khả dụng"),
    ("Could not import scanindex.core.kie.labeling_workspace: {} Saving will continue without validation.", "Không thể import scanindex.core.kie.labeling_workspace: {} Save vẫn tiếp tục nhưng KHÔNG được validate."),
    ("Validator crashed: {} Saving was cancelled.", "Validator crash: {} Save bị huỷ."),
    ("The file was written but could not be read back: {}", "Đã ghi file nhưng đọc lại không được: {}"),
    ("Post-save validation error", "Post-save validate lỗi"),
    ("Validator crashed while reloading the file: {}", "Validator crash khi reload file: {}"),
    ("✓ Refreshed", "✓ Đã làm mới"),
    ("✓ Copied {}", "✓ Đã copy {}"),
    ("Create signed_by relation", "Tạo relation signed_by"),
    ("Select {} (source):", "Chọn {} (từ):"),
    ("Select {} (target):", "Chọn {} (đến):"),
    ("Basic information", "Thông tin cơ bản"),
    ("Normalized value", "Giá trị chuẩn"),
    ("Confidence", "Độ tin cậy"),
    ("National header", "Quốc hiệu"),
    ("National motto", "Tiêu ngữ"),
    ("Superior authority", "Cơ quan cấp trên"),
    ("Issuing authority", "Cơ quan ban hành"),
    ("Document number / symbol", "Số / ký hiệu văn bản"),
    ("Document number and symbol", "Số, ký hiệu văn bản"),
    ("Place and issue date", "Địa danh & ngày ban hành"),
    ("Place and date", "Địa danh, ngày tháng"),
    ("Subject summary", "Trích yếu nội dung"),
    ("Addressee", "Nơi nhận (Kính gửi)"),
    ("Addressee", "Kính gửi"),
    ("Recipients", "Nơi nhận (danh sách)"),
    ("Recipients", "Nơi nhận"),
    ("Signer's title", "Chức vụ người ký"),
    ("Signer name", "Tên người ký"),
    ("Urgency level", "Mức độ khẩn"),
    ("Confidentiality", "Độ mật"),
    ("Circulation instructions", "Chỉ dẫn lưu hành"),
    ("Document type", "Loại văn bản"),
    ("✓ Saved", "✓ Đã lưu"),
    ("✓ Saved {}", "✓ Đã lưu {}"),
    ("⚠ Saved, but reload validation still reports {} errors", "⚠ Đã lưu nhưng reload validate còn {} lỗi"),
    ("✓ Saved ({} warnings)", "✓ Đã lưu ({} cảnh báo)"),
    ("✓ Saved and validation passed", "✓ Đã lưu + validate OK"),
    ("(dropped {} empty fields)", "(đã bỏ {} field trống)"),
    ("FILE LIST", "DANH SÁCH FILE"),
    ("KIE FIELDS", "TRƯỜNG KIE"),
    ("KIE REGION DETAILS", "CHI TIẾT VÙNG KIE"),
    ("No files are checked for deletion", "Chưa tick file nào để xoá"),
    ("… and {} other stems", "… và {} stem khác"),
    ("Partially deleted: {} files failed", "Xoá 1 phần: {} file lỗi"),
    ("Deleted {} files for {} stems", "Đã xoá {} file của {} stem"),
    ("No files checked", "Chưa check file nào"),
    ("Errors — CANNOT save", "Có lỗi — KHÔNG thể lưu"),
    ("The validator found {} required errors:", "Validator phát hiện {} lỗi bắt buộc phải sửa:"),
    ("Warnings", "Có cảnh báo"),
    ("The validator found no errors but reported {} warnings. Save anyway?", "Validator không thấy lỗi nhưng có {} cảnh báo. Bạn muốn vẫn lưu?"),
    ("POST-SAVE: written file has unexpected errors", "POST-SAVE: file đã ghi có lỗi bất thường"),
    ("The file was written, but validation after reloading still found errors. This is a bug; report it to technical support. Errors:", "File đã được ghi, nhưng khi đọc lại và validate thì còn lỗi. Đây là bug — hãy báo kỹ thuật. Nội dung lỗi:"),
    ("Save anyway", "Vẫn lưu"),
    ("Words ({})", "Từ ({})"),
    ("Relations ({})", "Quan hệ ({})"),
    ("{} KIE fields", "{} trường KIE"),
    ("* unsaved", "* chưa lưu"),
    ("The validator found {} errors:", "Validator phát hiện {} lỗi:"),
    ("POST-SAVE: written file still has errors", "POST-SAVE: file ghi xong vẫn còn lỗi"),
    ("The written file still fails validation after reload — this may be a viewer bug:", "File đã ghi nhưng reload validate vẫn báo lỗi — có thể là bug viewer:"),
)


UI_VALIDATION_AND_REPORT_TEXT_PAIRS: tuple[tuple[str, str], ...] = (
    # KIE validator details shown in the validation dialogs
    ("Duplicate field_id in label output: {}", "field_id bị trùng trong kết quả gán nhãn: {}"),
    ("Unknown field label: {} (raw_id={})", "Nhãn trường không xác định: {} (raw_id={})"),
    ("Unknown line_ids for {}: {}", "line_ids không xác định cho {}: {}"),
    ("Unknown word_ids for {}: {}", "word_ids không xác định cho {}: {}"),
    ("AMBIGUOUS_LINE_ONLY_FIELD for {} label={}: line_ids set but word_ids empty and text does not match full-line OCR text", "AMBIGUOUS_LINE_ONLY_FIELD cho {} nhãn={}: đã có line_ids nhưng word_ids rỗng và nội dung không khớp toàn bộ dòng OCR"),
    ("AMBIGUOUS_LINE_ONLY_FIELD for {} label={}: non-whitelist label cannot be auto-filled from line_ids alone", "AMBIGUOUS_LINE_ONLY_FIELD cho {} nhãn={}: nhãn ngoài danh sách cho phép không thể tự điền chỉ từ line_ids"),
    ("Field {} must contain at least one line_id or word_id", "Trường {} phải có ít nhất một line_id hoặc word_id"),
    ("word_ids do not belong to line_ids for {}: {}", "word_ids không thuộc line_ids của {}: {}"),
    ("Field {} spans multiple pages: {}", "Trường {} trải trên nhiều trang: {}"),
    ("Could not infer page_index for field {}", "Không suy ra được page_index cho trường {}"),
    ("page_index mismatch for field {}: {} vs {}", "page_index không khớp cho trường {}: {} so với {}"),
    ("Field {} has empty text", "Trường {} có nội dung rỗng"),
    ("confidence not numeric for field {}: {}", "confidence của trường {} không phải số: {}"),
    ("confidence out of range for field {}: {}", "confidence của trường {} nằm ngoài phạm vi: {}"),
    ("{} line contains '{}' in OCR but field text does not include it", "Dòng {} trong OCR có '{}' nhưng nội dung trường không chứa cụm này"),
    ("{} ({}) and {} ({}) share {} word_ids ({}%)", "{} ({}) và {} ({}) dùng chung {} word_ids ({}%)"),
    ("Unknown relation type: {}", "Loại quan hệ không xác định: {}"),
    ("Relation references unknown field ids: {}", "Quan hệ tham chiếu field id không xác định: {}"),
    ("signed_by relation must link SIGNER_ROLE -> SIGNER_NAME, got {} -> {} (raw from={} to={})", "Quan hệ signed_by phải nối SIGNER_ROLE -> SIGNER_NAME, nhưng nhận {} -> {} (raw từ={} đến={})"),
    ("confidence not numeric for relation {}: {}", "confidence của quan hệ {} không phải số: {}"),
    ("confidence out of range for relation {}: {}", "confidence của quan hệ {} nằm ngoài phạm vi: {}"),
    ("layoutlmv3_runtime_v1 must not contain page.kie_tokens", "layoutlmv3_runtime_v1 không được chứa page.kie_tokens"),
    ("layoutlmv3_runtime_v1 must not contain page.layout_regions", "layoutlmv3_runtime_v1 không được chứa page.layout_regions"),
    ("layoutlmv3_runtime_v1 must not contain page.table_structures", "layoutlmv3_runtime_v1 không được chứa page.table_structures"),
    ("layoutlmv3_training_v1 should contain page.kie_tokens", "layoutlmv3_training_v1 nên chứa page.kie_tokens"),
    ("layoutlmv3_training_v1 must not contain page.table_structures", "layoutlmv3_training_v1 không được chứa page.table_structures"),
    ("docx_export_v1 must not contain page.kie_tokens", "docx_export_v1 không được chứa page.kie_tokens"),

    # OCR accuracy report rendered in the result text area
    ("This software", "Phần mềm này"),
    ("Your software", "Phần mềm của bạn"),
    ("=== OCR ACCURACY COMPARISON RESULTS ===", "=== KẾT QUẢ SO SÁNH ĐỘ CHÍNH XÁC OCR ==="),
    ("Ground truth: {} characters / {} words", "Văn bản gốc: {} ký tự / {} từ"),
    ("✓ Excellent! Your OCR is about {} points better than this software (by CER).", "✓ Tuyệt vời! OCR của bạn tốt hơn phần mềm này khoảng {} điểm (theo CER)."),
    ("✓ Good. The difference is only {} points — the two results are comparable.", "✓ Tốt. Chênh lệch chỉ {} điểm — hai bên ngang ngửa."),
    ("⚠ Warning: Your OCR CER is {} points higher than this software. Check the OCR configuration.", "⚠ Cảnh báo: CER của OCR bạn cao hơn {} điểm so với phần mềm này. Nên kiểm tra lại cấu hình OCR."),
    ("Note: CER is the character error rate and WER is the word error rate. Lower values are more accurate.", "Ghi chú: CER = tỉ lệ lỗi ký tự, WER = tỉ lệ lỗi từ. Càng thấp càng chính xác hơn."),
)


UI_TEXT_PAIRS += UI_VALIDATION_AND_REPORT_TEXT_PAIRS
