#!/usr/bin/env python3
"""
OFFLINE MODEL DOWNLOADER for ScanIndex
======================================
Run ONCE after `git clone`. Populates `models/` from Hugging Face and
verifies every file against a hardcoded SHA256 manifest.

The manifest below (MODELS_CONFIG) is the trust anchor:

  - It lives in this script (committed to the GitHub repo) — not on HF —
    so an attacker who hijacks the welcomyou HF account cannot serve a
    different model. The script pins each repo to a specific commit
    SHA (`revision`) AND verifies SHA256 of every downloaded file.
  - Regenerate after any retrain / re-upload via:
        python scripts/refresh_model_hashes.py --apply

Trust anchors NOT covered here (separate channels):

  - Chrome ScreenAI: fetched from Google CDN by
    scanindex.core.ocr.screen_ai_downloader. Trusted via Google's
    signed Chrome extension (CRX) channel, not SHA256.
  - BAAI/bge-reranker-v2-m3: fetched lazily by sentence_transformers
    if the user enables Accurate search mode. Trusted via HF's own
    LFS hash + the upstream BAAI account. Not currently wired up in
    UI (UI passes None for the reranker arg).

Failure modes are loud: any hash mismatch, missing file, or HF error
halts the script with a non-zero exit. Better to fail than to leave the
app loading a tampered model.
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "models"


# ── BEGIN MODELS_CONFIG (auto-generated by refresh_model_hashes.py) ──
MODELS_CONFIG = [
    {
        "model_id":    'layoutlmv3-vn-admin-kie',
        "repo_id":     'welcomyou/layoutlmv3-vn-admin-kie',
        "type":        'huggingface',
        "sources":     ['layoutlmv3_fontgray_norm_final_epoch25'],
        "revision":    '095b51c7b8971491080ab4b5070f827541b24c27',
        "description": 'LayoutLMv3 KIE (Vietnamese admin docs, ONNX int8)',
        "integrity_files": {
            'layoutlmv3_fontgray_norm_final_epoch25/config.json': 'c912298610c61f73fa7c62c2ce23db2ccd9e5a3ef14a25b66b4532f7a9b65bb7',
            'layoutlmv3_fontgray_norm_final_epoch25/evaluation_batch_0006_final10_linebucket_pytorch.json': 'a6fc73d2acc1209ceeaff471ca9465cf6fa2bbfab1f972b14ed28e4b8138611d',
            'layoutlmv3_fontgray_norm_final_epoch25/evaluation_batch_0027_final10_linebucket_pytorch.json': '6c8385464b011a6671518d4cc7d2a4b81e6fdfd92304fcab1fc8442e1b3d1303',
            'layoutlmv3_fontgray_norm_final_epoch25/FINAL_MODEL_MANIFEST.json': '24324d1304631c96b8e99cb4470e3311fc2dadd032d9338011603559e13ae59a',
            'layoutlmv3_fontgray_norm_final_epoch25/label_list.json': '7c58422148d55753763d4b756c7334a532d4b440e1121b653dd0c6f59879bf85',
            'layoutlmv3_fontgray_norm_final_epoch25/layoutlmv3_fontgray_config.json': '46e371d1f8726309b6df4a9fec380813aaf8a90b793fe267f6d40ef8aad92f1e',
            'layoutlmv3_fontgray_norm_final_epoch25/layoutlmv3_fontgray_norm_final_epoch25.int8.onnx': '5cf74f1d478ce3b1667fbe8f2066bbcfb7b0e299a34e778c645e064ae9413a94',
            'layoutlmv3_fontgray_norm_final_epoch25/layoutlmv3_fontgray_report.md': 'a47eb743defe57cfe3939b4954e14200c71c2869d0b291db811720bbe51d7700',
            'layoutlmv3_fontgray_norm_final_epoch25/merges.txt': '1ce1664773c50f3e0cc8842619a93edc4624525b728b188a9e0be33b7726adc5',
            'layoutlmv3_fontgray_norm_final_epoch25/onnx_export_report.json': '4f4a222b593492f2aaa5d00b0f58e5373d241188608212e7e4939c01a487f9d2',
            'layoutlmv3_fontgray_norm_final_epoch25/special_tokens_map.json': '8293ae960b0a0852d4d3813118030a1149a3ed9fe37bc2e1e7b3c2e62eb2d4b7',
            'layoutlmv3_fontgray_norm_final_epoch25/tokenizer.json': '25a022a1227798b178474c838daf5d6ac925b6468fab9bc8456a48b6eb8168dd',
            'layoutlmv3_fontgray_norm_final_epoch25/tokenizer_config.json': '5e3ec8c526c862ec39465e7fc1cb3d0c6bc4305017a6ab72d06f7938cc0c761d',
            'layoutlmv3_fontgray_norm_final_epoch25/training_summary.json': '0baf0a045cc1c579357f19ff343203499f605b847a31bb850435eb9886f3db27',
            'layoutlmv3_fontgray_norm_final_epoch25/vocab.json': 'ed19656ea1707df69134c4af35c8ceda2cc9860bf2c3495026153a133670ab5e',
        },
    },
    {
        "model_id":    'e5-small-vn-archive-mix50',
        "repo_id":     'welcomyou/e5-small-vn-archive-mix50',
        "type":        'huggingface',
        "sources":     ['archive_models/e5-small-mix50-v2-onnx-fp32'],
        "revision":    'e700c6f6a57818df1843256c9668433850f33f3b',
        "description": 'E5-small mix50 v2 ONNX fp32 (archive embedder)',
        "integrity_files": {
            'archive_models/e5-small-mix50-v2-onnx-fp32/config.json': '51d8afcd56f9cdaf391c71abe73f1179fb52e71baa944234d27d070992917a9d',
            'archive_models/e5-small-mix50-v2-onnx-fp32/model.onnx': '4f203af8192028636d9eba2c6e60b6a224d64196492735dfb4d77f1ba7b172be',
            'archive_models/e5-small-mix50-v2-onnx-fp32/onnx_metadata.json': 'f53a7647df4ae429de9b6736d793f4158b004ef5e3e6c9c98889b525d0cade0f',
            'archive_models/e5-small-mix50-v2-onnx-fp32/sentencepiece.bpe.model': 'cfc8146abe2a0488e9e2a0c56de7952f7c11ab059eca145a0a727afce0db2865',
            'archive_models/e5-small-mix50-v2-onnx-fp32/special_tokens_map.json': '38d989b0fdad0fec0c67c14b1f3c8b68184022cf6d4adc5444526ced8653f738',
            'archive_models/e5-small-mix50-v2-onnx-fp32/tokenizer.json': '9a1e21e6d1e5cd51e1c5784f27451f04a2e44211197912a384531e818f0ec6ed',
            'archive_models/e5-small-mix50-v2-onnx-fp32/tokenizer_config.json': '65f5e8cbd6d2eb4cec9e437e58b96f0a21202dd94f0b84b702f979995ad6a770',
        },
    },
    {
        "model_id":    'distilled-protonx-vn-correction-ct2',
        "repo_id":     'welcomyou/distilled-protonx-vn-correction-ct2',
        "type":        'huggingface',
        "sources":     ['distilled_ct2'],
        "revision":    '431b1ce107e087eeba712cc965be1ff0b152e3c8',
        "description": 'distilled-protonx-legal-tc CT2 INT8 (Vietnamese OCR correction)',
        "integrity_files": {
            'distilled_ct2/config.json': 'f1859dad6c46f6b301b97634821e6f6f8928b6323293072e759ca68946dbf601',
            'distilled_ct2/model.bin': '6fb0cf50a4e88cdba55bdac27fc2dc0bde940b75c2f0bb3d49aaff9f3a35cb4f',
            'distilled_ct2/shared_vocabulary.json': 'e4f036c8b04caf4d64490edc317496054381b049eab4ca07921818bd71662b65',
            'distilled_ct2/special_tokens_map.json': '376715f787382b6e58a4dcfe18291cb638e2842746264ae7c72d7a665644ade4',
            'distilled_ct2/tokenizer.json': 'cca35916f8a7ede626a7b7693881ed02b7d54e6f0d0aa9ffa91204a70aaba782',
            'distilled_ct2/tokenizer_config.json': '42df28745766d788880e2f6d0bd4fef3c4639554db02100d5f1e92fc0374d609',
        },
    },
    {
        "model_id":    'lightgbm-vn-page-splitter',
        "repo_id":     'welcomyou/lightgbm-vn-page-splitter',
        "type":        'huggingface',
        "sources":     ['lightgbm_splitter'],
        "revision":    'e4fefddc6d01391789c380d1176852b0af1c566a',
        "description": 'LightGBM page splitter (doc_start + signer_page)',
        "integrity_files": {
            'lightgbm_splitter/doc_start/metadata.json': 'ca8e386b3995a037f9144146722c527617e993ff04cd5348dbd423de78ec666c',
            'lightgbm_splitter/doc_start/model.joblib': '8820e8210c7bc0431f9d4a8f99f76460fd79fb8a1a2b806cd039b553854c8882',
            'lightgbm_splitter/doc_start/model.txt': '5466227db768d24a9fe71e9d5c4d906581018a71e23a05c10cb7f5ffc508403c',
            'lightgbm_splitter/doc_start/report.json': 'c3b193b0e1e6937c9d336719e51de09655e1b0481edcd5e9abb1cdd7197392aa',
            'lightgbm_splitter/signer_page/metadata.json': '1d753f36d7e41af51fad34fbde25a5a2f07a339d7349cea6c0019dcfd3d4b89f',
            'lightgbm_splitter/signer_page/model.joblib': 'c06f23e9b937e50655c31e9336c8387d6fc2fc7cee1e65645e2043547453c8c9',
            'lightgbm_splitter/signer_page/model.txt': '6cb3e0a49016ddb01cba9e4b8fe5fb36d3cb847faef6a91e36b40cc0d2cc2168',
            'lightgbm_splitter/signer_page/report.json': 'e8f31ce678d6349344924a59f9610b1006072a72914228ff71f60d7475b0c883',
        },
    },
    {
        "model_id":    'doclayout-yolo-onnx-dynamic',
        "repo_id":     'welcomyou/doclayout-yolo-onnx-dynamic',
        "type":        'huggingface',
        "sources":     ['doclayout_yolo_onnx_dynamic', 'doclayout_yolo_doclaynet_onnx_dynamic'],
        "revision":    '997d2c6f44c742bc6e3ef94c795a62e57f2228b6',
        "description": 'DocLayout-YOLO ONNX dynamic-axes (DocStructBench + DocLayNet)',
        "integrity_files": {
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.names.json': '6c0c2cbc6b5456fc11e9435ad128cf10ca41579a49886a3b3b04e126d13d7516',
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.onnx': '6e7446c605119eab80a76f659a768dc4400a31b45a4f74b2246ae93c9358fc4f',
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.onnx.data': 'eb8399e798d1840a2d25cfd886eafb9bcd66482149c08c265607fafa650aa4dc',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.names.json': '552a83f6390099b6f362f242b447f3112fbbf6d7b13de3881a614433b3d30654',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.onnx': 'b783c66102a9172aa65206848e21872e355ac16607d0b9c20ea55c4699c2f200',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.onnx.data': 'c0f7356505b1c2f41f6d6251ca571c20571935ce92b7c7678df61e32a76c4214',
        },
    },
    {
        "model_id":    'gmft-tatr-onnx',
        "repo_id":     'welcomyou/gmft-tatr-onnx',
        "type":        'huggingface',
        "sources":     ['gmft_onnx'],
        "revision":    'ac122e4b1cb76f3e88649d984611992effbf168b',
        "description": 'GMFT-TATR ONNX (table detection + structure)',
        "integrity_files": {
            'gmft_onnx/detection/config.json': '36681fe7d60fe18ee72de10ee8e3ef27328db0f29b1da8a7d419764fab7c37c3',
            'gmft_onnx/detection/model.onnx': '5ff1ce079a5e213d96b8bcb1fc32edcca3f31f5ecf14b8bca0e872811f2a4003',
            'gmft_onnx/detection/model.onnx.data': 'f697d122334a94394f440fe3502db502cb06a42a3cc77bd349eb2fceadbef06e',
            'gmft_onnx/detection/preprocessor_config.json': '0a2867f42266778bf001854b38710dae46244cf135e6cce55b084a6c4beb7df1',
            'gmft_onnx/structure/config.json': '184496b7d3748d5080c2cff6e12da1b5d8e13f514167ff69bacef35d301eb7c3',
            'gmft_onnx/structure/model.onnx': '6d446a83cb32a928e02cf3d0875051e513e5fb8295b7c8763d1e28b52b31b631',
            'gmft_onnx/structure/model.onnx.data': '68d8c03c7cbae9d216703103c9134f98030aef8bc417d2e54a358c6f838b2c7e',
            'gmft_onnx/structure/preprocessor_config.json': '0a2867f42266778bf001854b38710dae46244cf135e6cce55b084a6c4beb7df1',
        },
    },
    {
        "model_id":    'docling-tableformer-v1-onnx-stepcache',
        "repo_id":     'welcomyou/docling-tableformer-v1-onnx-stepcache',
        "type":        'huggingface',
        "sources":     ['docling_tableformer_v1_stepcache_onnx'],
        "revision":    '76a8599f9210febac0cbfb43ce373fb15ccb6e3b',
        "description": 'Docling TableFormer v1 ONNX (stepcache decoder)',
        "integrity_files": {
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_bbox_decoder.onnx': 'c22d383ea9937ef81608cac7e8c7bd14671bb4fa91ba28c8f59deb16bd1d89a3',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_bbox_decoder.onnx.data': '926e28025d8ba150e50f4dd595e2e2363010cb9ede85210311378d2749788943',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_decoder_step.onnx': '806e8186385336dfb899789086c1592ebec080ec36ea745af6a38fd373b1754b',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_decoder_step.onnx.data': 'a3b67143919dc830d5217493d8fbbfa2cedd2ed1cbca857f0dc653a817f8e526',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_encoder.onnx': '29f488f91ac1a9d1f2e85f03e244eb427d46f83ef7666ca1986c41ecb898ed4d',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_encoder.onnx.data': 'ac35074b663e7473e4dfa56385363d0320e839a6e27c85bf1e589e903e69e022',
            'docling_tableformer_v1_stepcache_onnx/tm_config.json': '984e122ceb8ccf84d84c9d2882f6f2302a44b4f1e577babd6289892c36f3cffd',
        },
    },
    {
        "model_id":    'orientation-paddleocr',
        "repo_id":     'welcomyou/scanindex-models',
        "type":        'huggingface',
        "sources":     ['orientation'],
        "revision":    'f69ee24b57c09b5d00c3ce1c8c563e8621e5edcc',
        "description": 'PaddleOCR PP-LCNet 4-way page-orientation classifier',
        "integrity_files": {
            'orientation/PP-LCNet_x1_0_doc_ori.onnx': '76dc02d407066728872318a19263e3aeb31c19908b37b2e439343e14b3d5c4cf',
        },
    },
]
# ── END MODELS_CONFIG ──


# ── verification helpers (mirrors d:/App/asr-vn pattern) ────────────
class ModelIntegrityError(RuntimeError):
    pass


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as h:
        for chunk in iter(lambda: h.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve_under(base_dir: Path, relative_path: str) -> Path:
    """Resolve `relative_path` under `base_dir` and refuse path traversal."""
    base_resolved = base_dir.resolve()
    candidate = (base_dir / relative_path).resolve()
    if not candidate.is_relative_to(base_resolved):
        raise ModelIntegrityError(
            f"Path escapes {base_dir}: {relative_path}"
        )
    return candidate


def _require_keys(model_id: str, config: dict, *keys: str) -> None:
    missing = [k for k in keys if not config.get(k)]
    if missing:
        raise ModelIntegrityError(
            f"{model_id}: MODELS_CONFIG missing required keys "
            f"{missing}. Run scripts/refresh_model_hashes.py --apply."
        )


def _verify_one(file_path: Path, expected: str, label: str) -> None:
    actual = _sha256_file(file_path)
    if actual != expected:
        raise ModelIntegrityError(
            f"SHA256 mismatch for {label}\n"
            f"  Expected: {expected}\n"
            f"  Got:      {actual}"
        )


def _verify_integrity(model_id: str, integrity_files: dict[str, str]) -> None:
    for rel, expected in integrity_files.items():
        path = _resolve_under(MODELS_DIR, rel)
        if not path.exists():
            raise ModelIntegrityError(f"{model_id}: missing file {rel}")
        _verify_one(path, expected, f"{model_id}:{rel}")


def _local_paths_match(integrity_files: dict[str, str]) -> bool:
    """Quick check: are all expected files present and hash-correct already?"""
    try:
        for rel, expected in integrity_files.items():
            path = _resolve_under(MODELS_DIR, rel)
            if not path.exists():
                return False
            if _sha256_file(path) != expected:
                return False
        return True
    except Exception:
        return False


# ── tasks ───────────────────────────────────────────────────────────
def download_repo(config: dict) -> bool:
    model_id = config["model_id"]
    repo_id  = config["repo_id"]
    print(f"\n=== {model_id}  <-  {repo_id}")
    print(f"    {config.get('description', '')}")

    _require_keys(model_id, config, "type", "revision", "integrity_files", "sources")

    if _local_paths_match(config["integrity_files"]):
        print("    [skip] all files present and hash-verified")
        return True

    if config["type"] != "huggingface":
        raise ModelIntegrityError(
            f"{model_id}: unsupported type {config['type']!r}"
        )

    try:
        from huggingface_hub import snapshot_download
    except ImportError:
        print("    ERROR: pip install -U huggingface_hub")
        return False

    try:
        snapshot_download(
            repo_id=repo_id,
            repo_type="model",
            revision=config["revision"],
            local_dir=str(MODELS_DIR),
            local_dir_use_symlinks=False,
            allow_patterns=sorted(config["integrity_files"].keys()),
        )
    except Exception as e:
        print(f"    ERROR downloading: {e}")
        return False

    try:
        _verify_integrity(model_id, config["integrity_files"])
    except ModelIntegrityError as e:
        print(f"    INTEGRITY FAIL: {e}")
        return False

    print(f"    OK ({len(config['integrity_files'])} files verified)")
    return True


def download_screen_ai() -> bool:
    print("\n=== Chrome ScreenAI  <-  Google CDN")
    try:
        sys.path.insert(0, str(ROOT))
        from scanindex.core.ocr.screen_ai_downloader import (
            check_screen_ai, install_screen_ai,
        )
    except Exception as e:
        print(f"    SKIP (cannot import downloader: {e})")
        return False
    try:
        target = MODELS_DIR / "screen_ai"
        target.mkdir(parents=True, exist_ok=True)
        status = check_screen_ai(str(target))

        def _progress(done, total):
            if total:
                print(
                    f"\r    {done/1e6:5.1f}/{total/1e6:5.1f} MB"
                    f"  ({100*done/total:5.1f}%)",
                    end="", flush=True,
                )

        _, model_path, _ = install_screen_ai(
            str(target), status, progress_callback=_progress,
        )
        print(f"\n    OK ({model_path})")
        return True
    except Exception as e:
        print(f"\n    ERROR: {e}")
        return False


# ── main ────────────────────────────────────────────────────────────
def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", default=None,
                        help="Only download this model_id from MODELS_CONFIG")
    parser.add_argument("--skip-hf", action="store_true",
                        help="Skip all HF downloads (e.g. just ScreenAI)")
    parser.add_argument("--skip-screen-ai", action="store_true")
    args = parser.parse_args()

    if not MODELS_CONFIG:
        print("ERROR: MODELS_CONFIG is empty.\n"
              "Run scripts/refresh_model_hashes.py --apply first.",
              file=sys.stderr)
        return 1

    print(f"Project root: {ROOT}")
    print(f"Models dir:   {MODELS_DIR}")
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    results: dict[str, bool] = {}

    if not args.skip_hf:
        targets = MODELS_CONFIG
        if args.only:
            targets = [c for c in MODELS_CONFIG if c["model_id"] == args.only]
            if not targets:
                ids = ", ".join(c["model_id"] for c in MODELS_CONFIG)
                print(f"ERROR: --only {args.only!r} not in MODELS_CONFIG.\n"
                      f"Known model_ids: {ids}", file=sys.stderr)
                return 1
        for cfg in targets:
            results[cfg["model_id"]] = download_repo(cfg)

    if not args.skip_screen_ai and not args.only:
        results["screen_ai"] = download_screen_ai()

    print("\nSummary:")
    for k, v in results.items():
        print(f"  {k:50s} {'OK' if v else 'FAILED'}")
    return 0 if all(results.values()) else 2


if __name__ == "__main__":
    raise SystemExit(main())
