#!/usr/bin/env python3
"""
OFFLINE MODEL DOWNLOADER for ScanIndex
======================================
Run ONCE after `git clone`. Populates `models/` from pinned Hugging Face
snapshots, a pinned GitHub bootstrap asset, and Google's ScreenAI component
channel. Every downloaded file is verified before use.

The manifest below (MODELS_CONFIG) is the trust anchor:

  - It lives in this script (committed to the GitHub repo) — not on HF —
    so an attacker who hijacks the welcomyou HF account cannot serve a
    different model. The script pins each repo to a specific commit
    SHA (`revision`) AND verifies SHA256 of every downloaded file.
  - Regenerate after any retrain / re-upload via:
        python scripts/refresh_model_hashes.py --apply

Separate trust anchors:

  - Chrome ScreenAI: fetched from Google CDN by
    scanindex.core.ocr.screen_ai_downloader. Trusted via a pinned Google CDN
    fallback or the SHA256 announced by Google's updater XML, plus Authenticode
    verification of the extracted DLL.
  - Chrome ***REMOVED*** bootstrap: downloaded from a versioned GitHub Release
    asset and verified against the archive SHA256 plus per-file SHA256 pins.
Failure modes are loud: any hash mismatch, missing file, or HF error
halts the script with a non-zero exit. Better to fail than to leave the
app loading a tampered model.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Iterable
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = Path(os.environ.get("SCANINDEX_MODELS_DIR", ROOT / "models")).resolve()


# ── BEGIN MODELS_CONFIG (auto-generated by refresh_model_hashes.py) ──
MODELS_CONFIG = [
    {
        "model_id":    'layoutlmv3-vn-admin-kie',
        "repo_id":     'welcomyou/layoutlmv3-vn-admin-kie',
        "source_url":  'https://huggingface.co/welcomyou/layoutlmv3-vn-admin-kie/tree/5bc77cdd577e80c26ca7dd35f99a0960c06a1887',
        "type":        'huggingface',
        "sources":     ['layoutlmv3_fontgray_norm_final_epoch25'],
        "revision":    '5bc77cdd577e80c26ca7dd35f99a0960c06a1887',
        "description": 'LayoutLMv3 KIE (Vietnamese admin docs, ONNX int8)',
        "integrity_files": {
            'layoutlmv3_fontgray_norm_final_epoch25/config.json': 'a1a78025857baa6e7f18ad4c3b702ab22d9fba398cb15fd79bc37ff3a6472b93',
            'layoutlmv3_fontgray_norm_final_epoch25/label_list.json': '7c58422148d55753763d4b756c7334a532d4b440e1121b653dd0c6f59879bf85',
            'layoutlmv3_fontgray_norm_final_epoch25/layoutlmv3_fontgray_config.json': 'd296d886cf104b2eaa70b5b8397b0a7000161cb4908dbfde1948bf4a87b7bfd7',
            'layoutlmv3_fontgray_norm_final_epoch25/layoutlmv3_fontgray_norm_final_epoch25.int8.onnx': '99a67595e0d20d5fa33434734334416c64a704db66c5c51e927e21ec8b1f3db3',
            'layoutlmv3_fontgray_norm_final_epoch25/merges.txt': '1ce1664773c50f3e0cc8842619a93edc4624525b728b188a9e0be33b7726adc5',
            'layoutlmv3_fontgray_norm_final_epoch25/special_tokens_map.json': '8293ae960b0a0852d4d3813118030a1149a3ed9fe37bc2e1e7b3c2e62eb2d4b7',
            'layoutlmv3_fontgray_norm_final_epoch25/tokenizer.json': '25a022a1227798b178474c838daf5d6ac925b6468fab9bc8456a48b6eb8168dd',
            'layoutlmv3_fontgray_norm_final_epoch25/tokenizer_config.json': 'f726bf300393378f5db81dcd7db1562712a4fc694e6119a18f74523eead55a02',
            'layoutlmv3_fontgray_norm_final_epoch25/vocab.json': 'ed19656ea1707df69134c4af35c8ceda2cc9860bf2c3495026153a133670ab5e',
        },
    },
    {
        "model_id":    'distilled-protonx-vn-correction-ct2',
        "repo_id":     'welcomyou/distilled-protonx-vn-correction-ct2',
        "source_url":  'https://huggingface.co/welcomyou/distilled-protonx-vn-correction-ct2/tree/431b1ce107e087eeba712cc965be1ff0b152e3c8',
        "type":        'huggingface',
        "sources":     ['distilled_ct2'],
        "revision":    '431b1ce107e087eeba712cc965be1ff0b152e3c8',
        "description": 'distilled-protonx-legal-tc CT2 INT8 (Vietnamese OCR correction)',
        "integrity_files": {
            'distilled_ct2/config.json': 'f1859dad6c46f6b301b97634821e6f6f8928b6323293072e759ca68946dbf601',
            'distilled_ct2/model.bin': '6fb0cf50a4e88cdba55bdac27fc2dc0bde940b75c2f0bb3d49aaff9f3a35cb4f',
            'distilled_ct2/shared_vocabulary.json': 'e4f036c8b04caf4d64490edc317496054381b049eab4ca07921818bd71662b65',
            'distilled_ct2/special_tokens_map.json': '376715f787382b6e58a4dcfe18291cb638e2842746264ae7c72d7a665644ade4',
            'distilled_ct2/tokenizer.json': 'cca35916f8a7ede626a7b7693881ed02b7d54e6f0d0aa9ffa91204a70aaba782',
            'distilled_ct2/tokenizer_config.json': '42df28745766d788880e2f6d0bd4fef3c4639554db02100d5f1e92fc0374d609',
        },
    },
    {
        "model_id":    'lightgbm-vn-page-splitter',
        "repo_id":     'welcomyou/lightgbm-vn-page-splitter',
        "source_url":  'https://huggingface.co/welcomyou/lightgbm-vn-page-splitter/tree/e4fefddc6d01391789c380d1176852b0af1c566a',
        "type":        'huggingface',
        "sources":     ['lightgbm_splitter'],
        "revision":    'e4fefddc6d01391789c380d1176852b0af1c566a',
        "description": 'LightGBM page splitter (doc_start + signer_page)',
        "integrity_files": {
            'lightgbm_splitter/doc_start/metadata.json': 'ca8e386b3995a037f9144146722c527617e993ff04cd5348dbd423de78ec666c',
            'lightgbm_splitter/doc_start/model.txt': '5466227db768d24a9fe71e9d5c4d906581018a71e23a05c10cb7f5ffc508403c',
            'lightgbm_splitter/doc_start/report.json': 'c3b193b0e1e6937c9d336719e51de09655e1b0481edcd5e9abb1cdd7197392aa',
            'lightgbm_splitter/signer_page/metadata.json': '1d753f36d7e41af51fad34fbde25a5a2f07a339d7349cea6c0019dcfd3d4b89f',
            'lightgbm_splitter/signer_page/model.txt': '6cb3e0a49016ddb01cba9e4b8fe5fb36d3cb847faef6a91e36b40cc0d2cc2168',
            'lightgbm_splitter/signer_page/report.json': 'e8f31ce678d6349344924a59f9610b1006072a72914228ff71f60d7475b0c883',
        },
    },
    {
        "model_id":    'doclayout-yolo-onnx-dynamic',
        "repo_id":     'welcomyou/doclayout-yolo-onnx-dynamic',
        "source_url":  'https://huggingface.co/welcomyou/doclayout-yolo-onnx-dynamic/tree/997d2c6f44c742bc6e3ef94c795a62e57f2228b6',
        "type":        'huggingface',
        "sources":     ['doclayout_yolo_onnx_dynamic', 'doclayout_yolo_doclaynet_onnx_dynamic'],
        "revision":    '997d2c6f44c742bc6e3ef94c795a62e57f2228b6',
        "description": 'DocLayout-YOLO ONNX dynamic-axes (DocStructBench + DocLayNet)',
        "integrity_files": {
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.names.json': '6c0c2cbc6b5456fc11e9435ad128cf10ca41579a49886a3b3b04e126d13d7516',
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.onnx': '6e7446c605119eab80a76f659a768dc4400a31b45a4f74b2246ae93c9358fc4f',
            'doclayout_yolo_onnx_dynamic/doclayout_yolo_docstructbench_imgsz1024_dynamic.onnx.data': 'eb8399e798d1840a2d25cfd886eafb9bcd66482149c08c265607fafa650aa4dc',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.names.json': '552a83f6390099b6f362f242b447f3112fbbf6d7b13de3881a614433b3d30654',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.onnx': 'b783c66102a9172aa65206848e21872e355ac16607d0b9c20ea55c4699c2f200',
            'doclayout_yolo_doclaynet_onnx_dynamic/doclayout_yolo_doclaynet_imgsz1120_from_scratch_dynamic.onnx.data': 'c0f7356505b1c2f41f6d6251ca571c20571935ce92b7c7678df61e32a76c4214',
        },
    },
    {
        "model_id":    'gmft-tatr-onnx',
        "repo_id":     'welcomyou/gmft-tatr-onnx',
        "source_url":  'https://huggingface.co/welcomyou/gmft-tatr-onnx/tree/ac122e4b1cb76f3e88649d984611992effbf168b',
        "type":        'huggingface',
        "sources":     ['gmft_onnx'],
        "revision":    'ac122e4b1cb76f3e88649d984611992effbf168b',
        "description": 'GMFT-TATR ONNX (table detection + structure)',
        "integrity_files": {
            'gmft_onnx/detection/config.json': '36681fe7d60fe18ee72de10ee8e3ef27328db0f29b1da8a7d419764fab7c37c3',
            'gmft_onnx/detection/model.onnx': '5ff1ce079a5e213d96b8bcb1fc32edcca3f31f5ecf14b8bca0e872811f2a4003',
            'gmft_onnx/detection/model.onnx.data': 'f697d122334a94394f440fe3502db502cb06a42a3cc77bd349eb2fceadbef06e',
            'gmft_onnx/detection/preprocessor_config.json': '0a2867f42266778bf001854b38710dae46244cf135e6cce55b084a6c4beb7df1',
            'gmft_onnx/structure/config.json': '184496b7d3748d5080c2cff6e12da1b5d8e13f514167ff69bacef35d301eb7c3',
            'gmft_onnx/structure/model.onnx': '6d446a83cb32a928e02cf3d0875051e513e5fb8295b7c8763d1e28b52b31b631',
            'gmft_onnx/structure/model.onnx.data': '68d8c03c7cbae9d216703103c9134f98030aef8bc417d2e54a358c6f838b2c7e',
            'gmft_onnx/structure/preprocessor_config.json': '0a2867f42266778bf001854b38710dae46244cf135e6cce55b084a6c4beb7df1',
        },
    },
    {
        "model_id":    'docling-tableformer-v1-onnx-stepcache',
        "repo_id":     'welcomyou/docling-tableformer-v1-onnx-stepcache',
        "source_url":  'https://huggingface.co/welcomyou/docling-tableformer-v1-onnx-stepcache/tree/76a8599f9210febac0cbfb43ce373fb15ccb6e3b',
        "type":        'huggingface',
        "sources":     ['docling_tableformer_v1_stepcache_onnx'],
        "revision":    '76a8599f9210febac0cbfb43ce373fb15ccb6e3b',
        "description": 'Docling TableFormer v1 ONNX (stepcache decoder)',
        "integrity_files": {
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_bbox_decoder.onnx': 'c22d383ea9937ef81608cac7e8c7bd14671bb4fa91ba28c8f59deb16bd1d89a3',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_bbox_decoder.onnx.data': '926e28025d8ba150e50f4dd595e2e2363010cb9ede85210311378d2749788943',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_decoder_step.onnx': '806e8186385336dfb899789086c1592ebec080ec36ea745af6a38fd373b1754b',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_decoder_step.onnx.data': 'a3b67143919dc830d5217493d8fbbfa2cedd2ed1cbca857f0dc653a817f8e526',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_encoder.onnx': '29f488f91ac1a9d1f2e85f03e244eb427d46f83ef7666ca1986c41ecb898ed4d',
            'docling_tableformer_v1_stepcache_onnx/onnx/accurate/tableformer_accurate_encoder.onnx.data': 'ac35074b663e7473e4dfa56385363d0320e839a6e27c85bf1e589e903e69e022',
            'docling_tableformer_v1_stepcache_onnx/tm_config.json': '984e122ceb8ccf84d84c9d2882f6f2302a44b4f1e577babd6289892c36f3cffd',
        },
    },
    {
        "model_id":    'orientation-paddleocr',
        "repo_id":     'welcomyou/scanindex-models',
        "source_url":  'https://huggingface.co/welcomyou/scanindex-models/tree/8d2082f9d8921dac1e1c36ddf0ee60240ddee7f5',
        "type":        'huggingface',
        "sources":     ['orientation'],
        "revision":    '8d2082f9d8921dac1e1c36ddf0ee60240ddee7f5',
        "description": 'PaddleOCR PP-LCNet 4-way page-orientation classifier',
        "integrity_files": {
            'orientation/PP-LCNet_x1_0_doc_ori.onnx': '76dc02d407066728872318a19263e3aeb31c19908b37b2e439343e14b3d5c4cf',
        },
    },
]
# ── END MODELS_CONFIG ──


# ── verification helpers (mirrors d:/App/asr-vn pattern) ────────────
DIRECT_DOWNLOADS_CONFIG = [
    {
        "model_id": "***REMOVED***-en-vi-windows-x64",
        "type": "zip",
        "source_url": (
            "https://github.com/welcomyou/scanindex/releases/download/"
            "***REMOVED***/"
            "ScanIndex-***REMOVED***-win-x64-2025.11.24.0-en_vi-2024.10.8.1.zip"
        ),
        "archive_sha256": "***REMOVED***",
        "description": "Chrome ***REMOVED*** runtime + EN<->VI language pack bootstrap",
        "integrity_files": {
            "translate/en_vi/_metadata/verified_contents.json": "***REMOVED***",
            "translate/en_vi/en_vi_dictionary/dictionary.bin": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/decoder_init_0.tflite": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/decoder_step_0.tflite": "cc65767453aba9f21eae4b498e4e187fe93deefeb6609d7a3d3b55797b6b4c5d",
            "translate/en_vi/en_vi_nmt/encoder_0.tflite": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/processor_spec.pb": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/src_spm_model.model": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/src_spm_model.vocab": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/tgt_spm_model.model": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/tgt_spm_model.vocab": "***REMOVED***",
            "translate/en_vi/en_vi_nmt/translation_model.pb": "***REMOVED***",
            "translate/en_vi/manifest.json": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/decoder_init_0.tflite": "2d7b0a67592a6b2cf3bc17378d9c1fced057664f819c4b90b8ddf39b519ef2b9",
            "translate/en_vi/vi_en_nmt/decoder_step_0.tflite": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/encoder_0.tflite": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/processor_spec.pb": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/src_spm_model.model": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/src_spm_model.vocab": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/tgt_spm_model.model": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/tgt_spm_model.vocab": "***REMOVED***",
            "translate/en_vi/vi_en_nmt/translation_model.pb": "5963761a28c3fb6e4375f8ed6a2282b5db6a55042046a15f0e31940bc8aea856",
            "translate/lib***REMOVED***/arch_x64": "***REMOVED***",
            "translate/lib***REMOVED***/lib***REMOVED***.dll": "***REMOVED***",
            "translate/***REMOVED***.dll": "***REMOVED***",
        },
    },
]


class ModelIntegrityError(RuntimeError):
    pass


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as h:
        for chunk in iter(lambda: h.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve_under(base_dir: Path, relative_path: str) -> Path:
    """Resolve `relative_path` under `base_dir` and refuse path traversal."""
    base_resolved = base_dir.resolve()
    candidate = (base_dir / relative_path).resolve()
    if not candidate.is_relative_to(base_resolved):
        raise ModelIntegrityError(
            f"Path escapes {base_dir}: {relative_path}"
        )
    return candidate


def _require_keys(model_id: str, config: dict, *keys: str) -> None:
    missing = [k for k in keys if not config.get(k)]
    if missing:
        raise ModelIntegrityError(
            f"{model_id}: MODELS_CONFIG missing required keys "
            f"{missing}. Run scripts/refresh_model_hashes.py --apply."
        )


def _validate_sha256(value: str, label: str) -> None:
    if not re.fullmatch(r"[0-9a-f]{64}", str(value or "")):
        raise ModelIntegrityError(
            f"{label}: expected a lowercase 64-character SHA256 hex digest"
        )


def _validate_source_url(value: str, label: str) -> None:
    if not str(value or "").startswith("https://"):
        raise ModelIntegrityError(f"{label}: expected an https:// source URL")


def _validate_configs() -> None:
    for config in MODELS_CONFIG:
        model_id = config.get("model_id", "<missing model_id>")
        _require_keys(
            model_id, config, "repo_id", "source_url", "type", "revision",
            "integrity_files", "sources",
        )
        _validate_source_url(config["source_url"], f"{model_id}:source_url")
        if not re.fullmatch(r"[0-9a-f]{40}", config["revision"]):
            raise ModelIntegrityError(
                f"{model_id}: revision must be a lowercase 40-character git SHA"
            )
        for rel, expected in config["integrity_files"].items():
            _validate_sha256(expected, f"{model_id}:{rel}")

    for config in DIRECT_DOWNLOADS_CONFIG:
        model_id = config.get("model_id", "<missing model_id>")
        _require_keys(
            model_id, config, "source_url", "type", "archive_sha256",
            "integrity_files",
        )
        _validate_source_url(config["source_url"], f"{model_id}:source_url")
        _validate_sha256(config["archive_sha256"], f"{model_id}:archive_sha256")
        for rel, expected in config["integrity_files"].items():
            _validate_sha256(expected, f"{model_id}:{rel}")


def _validate_screen_ai_pins() -> int:
    sys.path.insert(0, str(ROOT))
    from scanindex.core.ocr.screen_ai_downloader import (
        PINNED_SCREEN_AI_COMPONENTS,
        validate_pinned_screen_ai_components,
    )

    validate_pinned_screen_ai_components()
    return len(PINNED_SCREEN_AI_COMPONENTS)


def _verify_one(file_path: Path, expected: str, label: str) -> None:
    _validate_sha256(expected, label)
    actual = _sha256_file(file_path)
    if actual != expected:
        raise ModelIntegrityError(
            f"SHA256 mismatch for {label}\n"
            f"  Expected: {expected}\n"
            f"  Got:      {actual}"
        )


def _verify_integrity(model_id: str, integrity_files: dict[str, str]) -> None:
    for rel, expected in integrity_files.items():
        path = _resolve_under(MODELS_DIR, rel)
        if not path.exists():
            raise ModelIntegrityError(f"{model_id}: missing file {rel}")
        _verify_one(path, expected, f"{model_id}:{rel}")


def _local_paths_match(integrity_files: dict[str, str]) -> bool:
    """Quick check: are all expected files present and hash-correct already?"""
    try:
        for rel, expected in integrity_files.items():
            path = _resolve_under(MODELS_DIR, rel)
            if not path.exists():
                return False
            if _sha256_file(path) != expected:
                return False
        return True
    except Exception:
        return False


# ── tasks ───────────────────────────────────────────────────────────
def _extract_zip_under_models(archive_path: Path) -> None:
    with zipfile.ZipFile(archive_path) as archive:
        for entry in archive.infolist():
            _resolve_under(MODELS_DIR, entry.filename)
        archive.extractall(MODELS_DIR)


def download_direct(config: dict) -> bool:
    model_id = config["model_id"]
    print(f"\n=== {model_id}  <-  {config['source_url']}")
    print(f"    {config.get('description', '')}")

    if _local_paths_match(config["integrity_files"]):
        print("    [skip] all files present and hash-verified")
        return True

    if config["type"] != "zip":
        raise ModelIntegrityError(
            f"{model_id}: unsupported direct download type {config['type']!r}"
        )

    archive_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".zip", delete=False) as tmp:
            archive_path = Path(tmp.name)
            request = Request(
                config["source_url"],
                headers={"User-Agent": "ScanIndex offline model downloader"},
            )
            with urlopen(request, timeout=120) as response:
                shutil.copyfileobj(response, tmp)

        _verify_one(
            archive_path, config["archive_sha256"], f"{model_id}:archive"
        )
        _extract_zip_under_models(archive_path)
        _verify_integrity(model_id, config["integrity_files"])
    except Exception as e:
        print(f"    ERROR downloading: {e}")
        return False
    finally:
        if archive_path:
            archive_path.unlink(missing_ok=True)

    print(f"    OK ({len(config['integrity_files'])} files verified)")
    return True


def download_repo(config: dict) -> bool:
    model_id = config["model_id"]
    repo_id  = config["repo_id"]
    print(f"\n=== {model_id}  <-  {repo_id}")
    print(f"    URL: {config['source_url']}")
    print(f"    {config.get('description', '')}")

    _require_keys(model_id, config, "type", "revision", "integrity_files", "sources")

    if _local_paths_match(config["integrity_files"]):
        print("    [skip] all files present and hash-verified")
        return True

    if config["type"] != "huggingface":
        raise ModelIntegrityError(
            f"{model_id}: unsupported type {config['type']!r}"
        )

    try:
        from huggingface_hub import snapshot_download
    except ImportError:
        print("    ERROR: pip install -U huggingface_hub")
        return False

    try:
        snapshot_download(
            repo_id=repo_id,
            repo_type="model",
            revision=config["revision"],
            local_dir=str(MODELS_DIR),
            allow_patterns=sorted(config["integrity_files"].keys()),
        )
    except Exception as e:
        print(f"    ERROR downloading: {e}")
        return False

    try:
        _verify_integrity(model_id, config["integrity_files"])
    except ModelIntegrityError as e:
        print(f"    INTEGRITY FAIL: {e}")
        return False

    print(f"    OK ({len(config['integrity_files'])} files verified)")
    return True


def download_screen_ai() -> bool:
    print("\n=== Chrome ScreenAI  <-  Google CDN")
    try:
        sys.path.insert(0, str(ROOT))
        from scanindex.core.ocr.screen_ai_downloader import (
            check_screen_ai, install_screen_ai,
        )
    except Exception as e:
        print(f"    SKIP (cannot import downloader: {e})")
        return False
    try:
        target = MODELS_DIR / "screen_ai"
        target.mkdir(parents=True, exist_ok=True)
        status = check_screen_ai(str(target))

        def _progress(done, total):
            if total:
                print(
                    f"\r    {done/1e6:5.1f}/{total/1e6:5.1f} MB"
                    f"  ({100*done/total:5.1f}%)",
                    end="", flush=True,
                )

        _, model_path, _ = install_screen_ai(
            str(target), status, progress_callback=_progress,
        )
        print(f"\n    OK ({model_path})")
        return True
    except Exception as e:
        print(f"\n    ERROR: {e}")
        return False


# ── main ────────────────────────────────────────────────────────────
def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure:
            reconfigure(errors="backslashreplace")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", default=None,
                        help="Only download this model_id")
    parser.add_argument("--skip-hf", action="store_true",
                        help="Skip all HF downloads (e.g. just ScreenAI)")
    parser.add_argument("--skip-direct", action="store_true",
                        help="Skip pinned direct-download bootstrap assets")
    parser.add_argument("--skip-screen-ai", action="store_true")
    parser.add_argument("--validate-config", action="store_true",
                        help="Validate URLs and 64-character SHA256 pins only")
    args = parser.parse_args()

    if not MODELS_CONFIG:
        print("ERROR: MODELS_CONFIG is empty.\n"
              "Run scripts/refresh_model_hashes.py --apply first.",
              file=sys.stderr)
        return 1

    print(f"Project root: {ROOT}")
    print(f"Models dir:   {MODELS_DIR}")
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    _validate_configs()
    screen_ai_pins = _validate_screen_ai_pins()
    if args.validate_config:
        hf_files = sum(len(c["integrity_files"]) for c in MODELS_CONFIG)
        direct_files = sum(
            len(c["integrity_files"]) for c in DIRECT_DOWNLOADS_CONFIG
        )
        print(
            f"OK: {len(MODELS_CONFIG)} HF sources / {hf_files} files, "
            f"{len(DIRECT_DOWNLOADS_CONFIG)} direct sources / {direct_files} "
            f"files, {screen_ai_pins} ScreenAI pins; "
            "every URL and SHA256 pin is valid."
        )
        return 0

    results: dict[str, bool] = {}

    if not args.skip_hf:
        targets = MODELS_CONFIG
        if args.only:
            targets = [c for c in MODELS_CONFIG if c["model_id"] == args.only]
        for cfg in targets:
            results[cfg["model_id"]] = download_repo(cfg)

    if not args.skip_direct:
        targets = DIRECT_DOWNLOADS_CONFIG
        if args.only:
            targets = [
                c for c in DIRECT_DOWNLOADS_CONFIG
                if c["model_id"] == args.only
            ]
        for cfg in targets:
            results[cfg["model_id"]] = download_direct(cfg)

    if args.only and not results:
        ids = ", ".join(
            c["model_id"] for c in MODELS_CONFIG + DIRECT_DOWNLOADS_CONFIG
        )
        print(
            f"ERROR: --only {args.only!r} is unknown.\nKnown model_ids: {ids}",
            file=sys.stderr,
        )
        return 1

    if not args.skip_screen_ai and not args.only:
        results["screen_ai"] = download_screen_ai()

    print("\nSummary:")
    for k, v in results.items():
        print(f"  {k:50s} {'OK' if v else 'FAILED'}")
    return 0 if all(results.values()) else 2


if __name__ == "__main__":
    raise SystemExit(main())

